FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    gnupg2 \
    apt-transport-https \
    ca-certificates \
    unixodbc \
    unixodbc-dev \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    curl -fsSL https://packages.microsoft.com/keys/microsoft.asc \
        | gpg --dearmor > /usr/share/keyrings/microsoft-prod.gpg; \
    curl -fsSL https://packages.microsoft.com/config/debian/12/prod.list \
        > /etc/apt/sources.list.d/mssql-release.list; \
    apt-get update; \
    ACCEPT_EULA=Y apt-get install -y --no-install-recommends msodbcsql17; \
    rm -rf /var/lib/apt/lists/*;

COPY pyproject.toml README.md manage.py /app/
COPY config /app/config
COPY apps /app/apps
COPY requirements /app/requirements

RUN pip install --upgrade pip \
    && pip install -r /app/requirements/local.txt \
    && pip install debugpy==1.8.5

RUN echo "openssl_conf = default_conf" > /etc/ssl/openssl_custom.cnf \
    && echo "[default_conf]" >> /etc/ssl/openssl_custom.cnf \
    && echo "ssl_conf = ssl_sect" >> /etc/ssl/openssl_custom.cnf \
    && echo "[ssl_sect]" >> /etc/ssl/openssl_custom.cnf \
    && echo "system_default = system_default_sect" >> /etc/ssl/openssl_custom.cnf \
    && echo "[system_default_sect]" >> /etc/ssl/openssl_custom.cnf \
    && echo "MinProtocol = TLSv1.0" >> /etc/ssl/openssl_custom.cnf \
    && echo "CipherString = DEFAULT@SECLEVEL=0" >> /etc/ssl/openssl_custom.cnf \
    && echo "Options = UnsafeLegacyServerConnect" >> /etc/ssl/openssl_custom.cnf

ENV OPENSSL_CONF=/etc/ssl/openssl_custom.cnf

EXPOSE 8000 5678 5679 5680
