# Generated by Django 5.2.13 on 2026-04-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComponenteCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("codigo", models.IntegerField(unique=True)),
                ("descricao", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "componente curricular",
                "verbose_name_plural": "componentes curriculares",
                "db_table": "componente_curricular",
            },
        ),
        migrations.CreateModel(
            name="AgrupamentoAtribuicaoTerritorioSaber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("cod_agrupamento", models.BigIntegerField(unique=True)),
                ("cod_territorio_saber", models.IntegerField()),
                (
                    "cod_experiencia_pedagogica",
                    models.IntegerField(blank=True, null=True),
                ),
                ("dt_inicio_atribuicao", models.DateTimeField()),
                ("ano_atribuicao", models.IntegerField()),
                (
                    "dt_fim_atribuicao",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("dt_fim_turma", models.DateTimeField(blank=True, null=True)),
                (
                    "rf_professor",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cod_turma",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cod_componentes_curriculares",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("ano_letivo", models.IntegerField()),
                (
                    "cod_motivo_disponibilizacao",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "desc_territorio_saber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "desc_experiencia_pedagogica",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "encerramento_atribuicao_agrupamento_atualizado",
                    models.BooleanField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "agrupamento atribuição território saber",
                "verbose_name_plural": "agrupamentos atribuição território saber",
                "db_table": "agrupamento_atribuicao_territorio_saber",
                "indexes": [
                    models.Index(
                        fields=["cod_turma"], name="idx_aats_cod_turma"
                    ),
                    models.Index(
                        fields=["rf_professor"], name="idx_aats_rf_professor"
                    ),
                    models.Index(
                        fields=["ano_letivo"], name="idx_aats_ano_letivo"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComponenteCurricularAgrupamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("componente_codigo", models.IntegerField()),
                ("turma_codigo", models.CharField(max_length=20)),
                ("codigo_agrupamento", models.BigIntegerField()),
                (
                    "rf_professor",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ano_letivo", models.IntegerField()),
            ],
            options={
                "verbose_name": "componente curricular agrupamento",
                "verbose_name_plural": "componentes curriculares agrupamento",
                "db_table": "componente_curricular_agrupamento",
                "indexes": [
                    models.Index(
                        fields=["turma_codigo"], name="idx_cca_turma_codigo"
                    ),
                    models.Index(
                        fields=["componente_codigo"],
                        name="idx_cca_componente_codigo",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "componente_codigo",
                            "turma_codigo",
                            "codigo_agrupamento",
                        ),
                        name="uq_componente_agrupamento",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ComponenteCurricularPorAnoLetivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("codigo_componente_curricular", models.IntegerField()),
                (
                    "descricao_componente_curricular",
                    models.CharField(max_length=300),
                ),
                (
                    "codigo_ano_turma",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "descricao_serie_ensino",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "codigo_serie_ensino",
                    models.IntegerField(blank=True, null=True),
                ),
                ("modalidade", models.IntegerField(blank=True, null=True)),
                ("ano_letivo", models.IntegerField()),
            ],
            options={
                "verbose_name": "componente curricular por ano letivo",
                "verbose_name_plural": "componentes curriculares por ano letivo",
                "db_table": "componente_curricular_por_ano_letivo",
                "indexes": [
                    models.Index(
                        fields=["ano_letivo", "modalidade"],
                        name="idx_ccal_ano_letivo_modalidade",
                    ),
                    models.Index(
                        fields=["codigo_ano_turma"],
                        name="idx_ccal_codigo_ano_turma",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "codigo_componente_curricular",
                            "ano_letivo",
                            "modalidade",
                        ),
                        name="uq_componente_por_ano_letivo",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ComponenteCurricularPorTurma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("codigo", models.IntegerField()),
                (
                    "codigo_componente_territorio_saber",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "codigo_componente_curricular_pai",
                    models.IntegerField(blank=True, null=True),
                ),
                ("descricao", models.CharField(max_length=300)),
                ("regencia", models.BooleanField()),
                ("planejamento_regencia", models.BooleanField()),
                ("territorio_saber", models.BooleanField()),
                (
                    "turma_codigo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("exibir_componente_eol", models.BooleanField()),
                (
                    "professor",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ano_letivo", models.IntegerField()),
            ],
            options={
                "verbose_name": "componente curricular por turma",
                "verbose_name_plural": "componentes curriculares por turma",
                "db_table": "componente_curricular_por_turma",
                "indexes": [
                    models.Index(
                        fields=["turma_codigo"], name="idx_ccpt_turma_codigo"
                    ),
                    models.Index(fields=["codigo"], name="idx_ccpt_codigo"),
                    models.Index(
                        fields=["ano_letivo"], name="idx_ccpt_ano_letivo"
                    ),
                    models.Index(
                        fields=["professor", "ano_letivo"],
                        name="idx_ccpt_prof_ano",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codigo", "turma_codigo", "professor"),
                        name="uq_componente_por_turma",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ComponenteCurricularRegencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("codigo", models.IntegerField()),
                (
                    "codigo_componente_territorio_saber",
                    models.IntegerField(blank=True, null=True),
                ),
                ("descricao", models.CharField(max_length=300)),
                ("territorio_saber", models.BooleanField()),
                (
                    "tipo_escola",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("turno_turma", models.IntegerField(blank=True, null=True)),
                ("componente_planejamento_regencia", models.BooleanField()),
                (
                    "turma_codigo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "professor",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ano_turma", models.CharField(max_length=10)),
                ("ano_letivo", models.IntegerField()),
                (
                    "inicio_atribuicao",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "fim_atribuicao",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "componente curricular regência",
                "verbose_name_plural": "componentes curriculares regência",
                "db_table": "componente_curricular_regencia",
                "indexes": [
                    models.Index(
                        fields=["ano_turma", "ano_letivo"],
                        name="idx_ccr_ano_turma_letivo",
                    ),
                    models.Index(
                        fields=["turma_codigo"], name="idx_ccr_turma_codigo"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "codigo",
                            "turma_codigo",
                            "professor",
                            "ano_letivo",
                        ),
                        name="uq_componente_regencia",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DadosAulaTurma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("componente_codigo", models.CharField(max_length=20)),
                ("componente_descricao", models.CharField(max_length=300)),
                ("turma_codigo", models.CharField(max_length=20)),
                (
                    "data_inicio_turma",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "ue_codigo",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ano_letivo", models.IntegerField(blank=True, null=True)),
                (
                    "tipo_periodicidade",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "dados aula turma",
                "verbose_name_plural": "dados aula turma",
                "db_table": "dados_aula_turma",
                "indexes": [
                    models.Index(
                        fields=["ue_codigo", "ano_letivo"],
                        name="idx_dat_ue_ano_letivo",
                    ),
                    models.Index(
                        fields=["turma_codigo"], name="idx_dat_turma_codigo"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("componente_codigo", "turma_codigo"),
                        name="uq_dados_aula_turma",
                    )
                ],
            },
        ),
    ]
