# Generated by Django 5.2.13 on 2026-04-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agrupamentoatribuicaoterritoriosaber",
            name="cod_agrupamento",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="componentecurricularagrupamento",
            name="codigo_agrupamento",
            field=models.BigIntegerField(),
        ),
    ]
