# Generated by Django 5.2.13 on 2026-04-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponenteCurricularPAP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_componente_curricular", models.IntegerField(unique=True)),
            ],
            options={
                "db_table": "componentecurricularpap",
            },
        ),
        migrations.CreateModel(
            name="RegenciaComponenteCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_componente_curricular", models.IntegerField()),
                ("turno", models.IntegerField(blank=True, null=True)),
                ("ano", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "regenciacomponentecurricular",
            },
        ),
        migrations.RenameModel(
            old_name="DadosAulaTurma",
            new_name="ComponenteInicioTurma",
        ),
        migrations.RenameModel(
            old_name="ComponenteCurricularPorAnoLetivo",
            new_name="GradeCurricularSerie",
        ),
        migrations.DeleteModel(
            name="ComponenteCurricularRegencia",
        ),
        migrations.AlterModelOptions(
            name="componenteinicioturma",
            options={
                "verbose_name": "componente início turma",
                "verbose_name_plural": "componentes início turma",
            },
        ),
        migrations.AlterModelOptions(
            name="gradecurricularserie",
            options={
                "verbose_name": "grade curricular série",
                "verbose_name_plural": "grades curriculares série",
            },
        ),
        migrations.RemoveConstraint(
            model_name="componenteinicioturma",
            name="uq_dados_aula_turma",
        ),
        migrations.RemoveConstraint(
            model_name="gradecurricularserie",
            name="uq_componente_por_ano_letivo",
        ),
        migrations.RenameIndex(
            model_name="gradecurricularserie",
            new_name="idx_gcs_ano_letivo_modalidade",
            old_name="idx_ccal_ano_letivo_modalidade",
        ),
        migrations.RenameIndex(
            model_name="gradecurricularserie",
            new_name="idx_gcs_codigo_ano_turma",
            old_name="idx_ccal_codigo_ano_turma",
        ),
        migrations.AddConstraint(
            model_name="componenteinicioturma",
            constraint=models.UniqueConstraint(
                fields=("componente_codigo", "turma_codigo"),
                name="uq_componente_inicio_turma",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradecurricularserie",
            constraint=models.UniqueConstraint(
                fields=(
                    "codigo_componente_curricular",
                    "ano_letivo",
                    "modalidade",
                ),
                name="uq_grade_curricular_serie",
                nulls_distinct=False,
            ),
        ),
        migrations.AlterModelTable(
            name="componenteinicioturma",
            table="componente_inicio_turma",
        ),
        migrations.AlterModelTable(
            name="gradecurricularserie",
            table="grade_curricular_serie",
        ),
    ]
