# Generated by Django 5.2.13 on 2026-04-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pedagogico",
            "0002_componentecurricularpap_regenciacomponentecurricular_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TurmaItinerarioEnsinoMedio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "serie",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "turmaitinerarioensinomedio",
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("codigo", models.BigIntegerField(unique=True)),
                ("ano_letivo", models.IntegerField()),
                ("ano", models.CharField(blank=True, max_length=5, null=True)),
                ("tipo_turma", models.IntegerField()),
                ("nome_turma", models.CharField(max_length=200)),
                ("duracao_turno", models.IntegerField(blank=True, null=True)),
                ("tipo_turno", models.IntegerField(blank=True, null=True)),
                (
                    "data_inicio_turma",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                ("extinta", models.BooleanField(default=False)),
                (
                    "situacao",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("ue_codigo", models.CharField(max_length=20)),
                (
                    "modalidade",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "codigo_modalidade",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "semestre",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("ensino_especial", models.BooleanField(default=False)),
                (
                    "serie_ensino",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "data_status_turma_escola",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "turma",
                "verbose_name_plural": "turmas",
                "db_table": "turma",
                "indexes": [
                    models.Index(
                        fields=["ue_codigo", "ano_letivo"],
                        name="idx_turma_ue_ano",
                    ),
                    models.Index(fields=["tipo_turma"], name="idx_turma_tipo"),
                    models.Index(
                        fields=["ano_letivo"], name="idx_turma_ano_letivo"
                    ),
                ],
            },
        ),
    ]
