# Generated by Django 5.2.13 on 2026-05-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0003_turmaitinerarioensinomedio_turma"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtribuicaoComponente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("turma_codigo", models.CharField(max_length=20)),
                ("componente_codigo", models.IntegerField()),
                (
                    "professor",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("atribuicao_externa", models.BooleanField(default=False)),
                ("ano_letivo", models.IntegerField()),
            ],
            options={
                "verbose_name": "atribuição componente",
                "verbose_name_plural": "atribuições componente",
                "db_table": "atribuicao_componente",
            },
        ),
        migrations.CreateModel(
            name="ComponenteTurma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("turma_codigo", models.CharField(max_length=20)),
                ("componente_codigo", models.IntegerField()),
                ("descricao", models.CharField(max_length=300)),
                ("regencia", models.BooleanField()),
                ("planejamento_regencia", models.BooleanField()),
                ("territorio_saber", models.BooleanField()),
                (
                    "codigo_componente_territorio_saber",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "codigo_componente_curricular_pai",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tipo_escola",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("turno_turma", models.IntegerField(blank=True, null=True)),
                (
                    "ano_turma",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ano_letivo", models.IntegerField()),
            ],
            options={
                "verbose_name": "componente turma",
                "verbose_name_plural": "componentes turma",
                "db_table": "componente_turma",
            },
        ),
        migrations.CreateModel(
            name="GradeComponenteCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("codigo_componente_curricular", models.IntegerField()),
                (
                    "descricao_componente_curricular",
                    models.CharField(max_length=300),
                ),
                (
                    "codigo_ano_turma",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "descricao_serie_ensino",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "codigo_serie_ensino",
                    models.IntegerField(blank=True, null=True),
                ),
                ("modalidade", models.IntegerField(blank=True, null=True)),
                ("ano_letivo", models.IntegerField()),
            ],
            options={
                "verbose_name": "grade componente curricular",
                "verbose_name_plural": "grades componente curricular",
                "db_table": "grade_componente_curricular",
            },
        ),
        migrations.DeleteModel(
            name="ComponenteCurricularPorTurma",
        ),
        migrations.DeleteModel(
            name="ComponenteInicioTurma",
        ),
        migrations.DeleteModel(
            name="GradeCurricularSerie",
        ),
        migrations.AlterModelTable(
            name="componentecurricularpap",
            table="componente_curricular_pap",
        ),
        migrations.AlterModelTable(
            name="regenciacomponentecurricular",
            table="regencia_componente_curricular",
        ),
        migrations.AlterModelTable(
            name="turmaitinerarioensinomedio",
            table="turma_itinerario_ensino_medio",
        ),
        migrations.AddIndex(
            model_name="atribuicaocomponente",
            index=models.Index(
                fields=["turma_codigo"], name="idx_ac_turma_codigo"
            ),
        ),
        migrations.AddIndex(
            model_name="atribuicaocomponente",
            index=models.Index(
                fields=["componente_codigo"], name="idx_ac_componente_codigo"
            ),
        ),
        migrations.AddIndex(
            model_name="atribuicaocomponente",
            index=models.Index(
                fields=["professor", "ano_letivo"], name="idx_ac_prof_ano"
            ),
        ),
        migrations.AddConstraint(
            model_name="atribuicaocomponente",
            constraint=models.UniqueConstraint(
                fields=("turma_codigo", "componente_codigo", "professor"),
                name="uq_atribuicao_componente",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="componenteturma",
            index=models.Index(
                fields=["turma_codigo"], name="idx_ct_turma_codigo"
            ),
        ),
        migrations.AddIndex(
            model_name="componenteturma",
            index=models.Index(
                fields=["componente_codigo"], name="idx_ct_componente_codigo"
            ),
        ),
        migrations.AddIndex(
            model_name="componenteturma",
            index=models.Index(
                fields=["ano_letivo"], name="idx_ct_ano_letivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="componenteturma",
            constraint=models.UniqueConstraint(
                fields=("turma_codigo", "componente_codigo"),
                name="uq_componente_turma",
            ),
        ),
        migrations.AddIndex(
            model_name="gradecomponentecurricular",
            index=models.Index(
                fields=["ano_letivo", "modalidade"],
                name="idx_gcc_ano_letivo_modalidade",
            ),
        ),
        migrations.AddIndex(
            model_name="gradecomponentecurricular",
            index=models.Index(
                fields=["codigo_ano_turma"], name="idx_gcc_codigo_ano_turma"
            ),
        ),
        migrations.AddConstraint(
            model_name="gradecomponentecurricular",
            constraint=models.UniqueConstraint(
                fields=(
                    "codigo_componente_curricular",
                    "ano_letivo",
                    "modalidade",
                    "codigo_ano_turma",
                ),
                name="uq_grade_componente_curricular",
                nulls_distinct=False,
            ),
        ),
    ]
