# Generated by Django 5.2.13 on 2026-05-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0004_atribuicaocomponente_componenteturma_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="componenteturma",
            name="codigo_serie_ensino",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="turma",
            name="codigo_modalidade_etapa",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="turma",
            name="codigo_tipo_programa",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
