# Generated by Django 5.2.13 on 2026-05-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0005_componenteturma_codigo_serie_ensino_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponenteCurricularHierarquia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_componente_curricular_pai",
                    models.IntegerField(db_column="idcomponentecurricularpai"),
                ),
                (
                    "id_componente_curricular",
                    models.IntegerField(db_column="idcomponentecurricular"),
                ),
                ("vigencia", models.DateTimeField()),
            ],
            options={
                "db_table": "componente_curricular_hierarquia",
            },
        ),
        migrations.RenameModel(
            old_name="RegenciaComponenteCurricular",
            new_name="ComponenteCurricularPlanejamentoRegencia",
        ),
        migrations.RemoveIndex(
            model_name="componenteturma",
            name="idx_ct_ano_letivo",
        ),
        migrations.RemoveField(
            model_name="componenteturma",
            name="ano_letivo",
        ),
        migrations.RemoveField(
            model_name="componenteturma",
            name="ano_turma",
        ),
        migrations.RemoveField(
            model_name="componenteturma",
            name="codigo_componente_curricular_pai",
        ),
        migrations.RemoveField(
            model_name="componenteturma",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="componenteturma",
            name="planejamento_regencia",
        ),
        migrations.RemoveField(
            model_name="componenteturma",
            name="regencia",
        ),
        migrations.RemoveField(
            model_name="componenteturma",
            name="territorio_saber",
        ),
        migrations.RemoveField(
            model_name="componenteturma",
            name="tipo_escola",
        ),
        migrations.RemoveField(
            model_name="componenteturma",
            name="turno_turma",
        ),
        migrations.AddField(
            model_name="componentecurricular",
            name="regencia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="turma",
            name="codigo_serie_ensino",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="componentecurricularplanejamentoregencia",
            table="componente_curricular_planejamento_regencia",
        ),
    ]
