# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0006_componentecurricularhierarquia_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gradecomponentecurricular",
            name="uq_grade_componente_curricular",
        ),
        migrations.AddConstraint(
            model_name="gradecomponentecurricular",
            constraint=models.UniqueConstraint(
                fields=(
                    "codigo_componente_curricular",
                    "ano_letivo",
                    "modalidade",
                    "codigo_ano_turma",
                    "codigo_serie_ensino",
                ),
                name="uq_grade_componente_curricular",
                nulls_distinct=False,
            ),
        ),
    ]
