# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0007_altera_unique_grade_componente_curricular"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="turma",
            index=models.Index(
                fields=[
                    "ue_codigo",
                    "ano_letivo",
                    "codigo_modalidade_etapa",
                    "codigo",
                ],
                name="idx_turma_ue_ano_mod_codigo",
            ),
        ),
        migrations.AddIndex(
            model_name="turma",
            index=models.Index(
                fields=[
                    "ue_codigo",
                    "ano_letivo",
                    "codigo_tipo_programa",
                ],
                name="idx_turma_ue_ano_programa",
            ),
        ),
        migrations.AddIndex(
            model_name="componentecurricularhierarquia",
            index=models.Index(
                fields=["id_componente_curricular", "-vigencia"],
                name="idx_cch_comp_vigencia",
            ),
        ),
    ]
