# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0008_indices_performance_componentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="atribuicaocomponente",
            name="id_atribuicao_origem",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaocomponente",
            name="dt_atribuicao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaocomponente",
            name="dt_cancelamento",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaocomponente",
            name="dt_disponibilizacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaocomponente",
            name="cd_motivo_disponibilizacao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="atribuicaocomponente",
            index=models.Index(
                condition=models.Q(
                    ("dt_cancelamento__isnull", True),
                    ("dt_disponibilizacao__isnull", True),
                ),
                fields=["professor", "ano_letivo"],
                name="idx_ac_prof_ano_vigente",
            ),
        ),
        migrations.AddIndex(
            model_name="atribuicaocomponente",
            index=models.Index(
                fields=[
                    "turma_codigo",
                    "professor",
                    "componente_codigo",
                    "ano_letivo",
                ],
                name="idx_ac_turma_prof_comp_ano",
            ),
        ),
    ]
