# Generated by Django 5.2.15 on 2026-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0011_turma_codigo_etapa_ciclo_ensino"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="codigo_grade_programa",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="turma",
            name="descricao_grade_programa",
            field=models.CharField(default="NAO INFORMADA", max_length=200),
        ),
        migrations.AddField(
            model_name="turma",
            name="tipo_escola",
            field=models.IntegerField(default=0),
        ),
    ]
