# Generated by Django 5.2.15 on 2026-06-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0012_turma_codigo_grade_programa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="tipo_grade_programa",
            field=models.IntegerField(default=0),
        ),
    ]
