# Generated by Django 5.2.16 on 2026-07-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0018_remove_unique_agrupamento_api_eol"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurmaAtribuidaDreUe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("codigo_escola", models.CharField(max_length=6)),
                ("codigo_turma", models.BigIntegerField()),
                ("ano_letivo", models.IntegerField()),
                (
                    "modalidade",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("semestre", models.IntegerField(blank=True, null=True)),
                (
                    "codigo_modalidade",
                    models.IntegerField(blank=True, null=True),
                ),
                ("codigo_dre", models.CharField(max_length=6)),
                (
                    "dre",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "dre_abreviacao",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("ue", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "ue_abreviacao",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "nome_turma",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "ano",
                    models.CharField(blank=True, max_length=18, null=True),
                ),
                (
                    "tipo_ue",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("codigo_tipo_ue", models.IntegerField(blank=True, null=True)),
                (
                    "codigo_tipo_escola",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tipo_escola",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("duracao_turno", models.IntegerField(blank=True, null=True)),
                ("tipo_turno", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "turma atribuída DRE UE",
                "verbose_name_plural": "turmas atribuídas DRE UE",
                "db_table": "turma_atribuida_dre_ue",
            },
        ),
        migrations.AddIndex(
            model_name="atribuicaocomponente",
            index=models.Index(
                condition=models.Q(("dt_cancelamento__isnull", True)),
                fields=["professor", "ano_letivo", "componente_codigo"],
                name="idx_ac_prof_ano_comp_vig",
            ),
        ),
        migrations.AddIndex(
            model_name="turmaatribuidadreue",
            index=models.Index(
                fields=["codigo_escola"], name="idx_tadu_codigo_escola"
            ),
        ),
        migrations.AddIndex(
            model_name="turmaatribuidadreue",
            index=models.Index(
                fields=["codigo_dre"], name="idx_tadu_codigo_dre"
            ),
        ),
        migrations.AddIndex(
            model_name="turmaatribuidadreue",
            index=models.Index(
                fields=["ano_letivo"], name="idx_tadu_ano_letivo"
            ),
        ),
        migrations.AddIndex(
            model_name="turmaatribuidadreue",
            index=models.Index(fields=["codigo_turma"], name="idx_tadu_turma"),
        ),
    ]
