# Generated by Django 5.2.15 on 2026-07-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0020_componenteturma_tipo_escola"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="codigo_tipo_periodicidade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
