# Generated by Django 5.2.15 on 2026-08-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0021_turma_codigo_tipo_periodicidade"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponenteCurricularApiEol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                (
                    "id_relacao_origem",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("id_componente_curricular", models.IntegerField()),
                ("eh_regencia", models.BooleanField()),
                ("eh_territorio", models.BooleanField()),
                (
                    "descricao",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "id_componente_curricular_pai",
                    models.IntegerField(blank=True, null=True),
                ),
                ("vigencia", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "componente curricular da API EOL",
                "verbose_name_plural": (
                    "componentes curriculares da API EOL"
                ),
                "db_table": "componente_curricular_api_eol",
                "indexes": [
                    models.Index(
                        fields=["id_componente_curricular"],
                        name="idx_cc_api_eol_componente",
                    ),
                    models.Index(
                        fields=["id_componente_curricular_pai"],
                        name="idx_cc_api_eol_pai",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "id_relacao_origem",
                            "id_componente_curricular",
                        ),
                        name="uq_cc_api_eol_relacao_componente",
                        nulls_distinct=False,
                    ),
                ],
            },
        ),
    ]
