# Generated by Django 5.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0021_turma_codigo_tipo_periodicidade"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapaEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("codigo", models.IntegerField(unique=True)),
                ("descricao", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "etapa ensino",
                "verbose_name_plural": "etapas ensino",
                "db_table": "etapa_ensino",
            },
        ),
    ]
