# Generated by Django 5.2.15 on 2026-08-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0022_etapa_ensino"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="data_fim_turma",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
