# Generated by Django 5.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogico", "0024_turma_data_fim_turma"),
    ]

    operations = [
        migrations.CreateModel(
            name="CicloEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transferido_em", models.DateTimeField()),
                ("codigo_modalidade_ensino", models.IntegerField()),
                ("codigo_etapa_ensino", models.IntegerField()),
                ("codigo", models.IntegerField(unique=True)),
                ("descricao", models.CharField(max_length=300)),
                ("data_atualizacao", models.DateTimeField()),
            ],
            options={
                "verbose_name": "ciclo de ensino",
                "verbose_name_plural": "ciclos de ensino",
                "db_table": "ciclo_ensino",
            },
        ),
    ]
