# Generated by Django 5.2.17 on 2026-09-22 19:44

from django.contrib.postgres.operations import AddIndexConcurrently
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("pedagogico", "0026_turma_data_inicio"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="atribuicaocomponente",
            index=models.Index(
                condition=models.Q(("dt_cancelamento__isnull", True)),
                fields=["turma_codigo", "componente_codigo"],
                name="idx_ac_turma_componente_ativa",
            ),
        ),
        AddIndexConcurrently(
            model_name="turma",
            index=models.Index(
                django.db.models.functions.comparison.Cast(
                    models.F("codigo"), output_field=models.CharField()
                ),
                name="idx_turma_codigo_varchar",
            ),
        ),
    ]
