# Generated by Django 5.2.13 on 2026-04-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComponenteCurricularPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_componente_curricular",
                    models.BigIntegerField(
                        help_text="EOL cd_componente_curricular.", unique=True
                    ),
                ),
                (
                    "nome_componente_curricular",
                    models.CharField(
                        help_text="EOL dc_componente_curricular.", max_length=200
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[("PAP", "PAP"), ("PAEE", "PAEE")],
                        help_text="'PAP' ou 'PAEE'.",
                        max_length=10,
                    ),
                ),
                (
                    "vigente",
                    models.BooleanField(
                        help_text="True = componente ativo; False = legado (substituído por versão mais nova)."
                    ),
                ),
            ],
            options={
                "verbose_name": "componente curricular de programa",
                "verbose_name_plural": "componentes curriculares de programa",
                "db_table": "componente_curricular_programa",
            },
        ),
        migrations.CreateModel(
            name="TipoPrograma",
            fields=[
                (
                    "codigo_tipo_programa",
                    models.IntegerField(
                        help_text="Mesmo ID do EOL (cd_tipo_programa).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[("PAP", "PAP"), ("PAEE", "PAEE")],
                        help_text="'PAP' ou 'PAEE'.",
                        max_length=10,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "tipo de programa",
                "verbose_name_plural": "tipos de programa",
                "db_table": "tipo_programa",
            },
        ),
        migrations.CreateModel(
            name="MatriculaTurmaPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_aluno",
                    models.BigIntegerField(
                        help_text="EOL cd_aluno — FK lógica para aluno (PEDAGOGICO_DB — banco diferente)."
                    ),
                ),
                (
                    "codigo_turma",
                    models.BigIntegerField(
                        help_text="FK lógica → turma_programa.codigo_turma."
                    ),
                ),
                (
                    "codigo_componente_curricular",
                    models.BigIntegerField(
                        help_text="FK lógica → componente_curricular_programa.codigo_componente_curricular."
                    ),
                ),
                (
                    "nome_componente_curricular",
                    models.CharField(
                        help_text="EOL dc_componente_curricular — desnormalizado para evitar JOIN.",
                        max_length=200,
                    ),
                ),
                (
                    "codigo_situacao_matricula",
                    models.SmallIntegerField(help_text="EOL st_matricula."),
                ),
                (
                    "descricao_situacao_matricula",
                    models.CharField(
                        help_text="Ex: 'Ativo', 'Concluído' — desnormalizado para evitar mapeamento em código.",
                        max_length=50,
                    ),
                ),
                (
                    "data_matricula",
                    models.DateField(help_text="EOL dt_status_matricula."),
                ),
                (
                    "data_situacao",
                    models.DateField(
                        blank=True, help_text="EOL dt_situacao_aluno.", null=True
                    ),
                ),
                (
                    "ano_letivo",
                    models.SmallIntegerField(
                        help_text="Desnormalizado da turma — necessário para filtros diretos por ano."
                    ),
                ),
                (
                    "codigo_ue",
                    models.CharField(
                        help_text="Desnormalizado da turma — exigido por AlunoTurmaPapDto.",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_dre",
                    models.CharField(
                        help_text="Desnormalizado da turma — exigido por AlunoTurmaPapDto.",
                        max_length=20,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[("PAP", "PAP"), ("PAEE", "PAEE")],
                        help_text="'PAP' ou 'PAEE' — desnormalizado da turma para filtros diretos.",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Última atualização pelo ETL — usado no incremental.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "matrícula em turma de programa",
                "verbose_name_plural": "matrículas em turmas de programa",
                "db_table": "matricula_turma_programa",
                "indexes": [
                    models.Index(fields=["codigo_aluno"], name="idx_matricula_aluno"),
                    models.Index(fields=["ano_letivo"], name="idx_matricula_ano"),
                    models.Index(fields=["codigo_ue"], name="idx_matricula_ue"),
                    models.Index(fields=["categoria"], name="idx_matricula_categoria"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "codigo_turma",
                            "codigo_aluno",
                            "codigo_componente_curricular",
                        ),
                        name="uq_matricula_turma_aluno_componente",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TurmaPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_turma",
                    models.BigIntegerField(
                        help_text="EOL cd_turma_escola.", unique=True
                    ),
                ),
                (
                    "nome_turma",
                    models.CharField(
                        help_text="EOL dc_turma_escola — equivale a TurmaNome / NomeFiltro do Elastic.",
                        max_length=200,
                    ),
                ),
                (
                    "codigo_ue",
                    models.CharField(help_text="EOL escola.cd_escola.", max_length=20),
                ),
                (
                    "codigo_dre",
                    models.CharField(
                        help_text="EOL unidade_administrativa.cd_unidade_administrativa.",
                        max_length=20,
                    ),
                ),
                (
                    "ano_letivo",
                    models.SmallIntegerField(help_text="EOL turma_escola.an_letivo."),
                ),
                (
                    "tipo_turno",
                    models.SmallIntegerField(
                        blank=True, help_text="EOL cd_tipo_turno.", null=True
                    ),
                ),
                (
                    "descricao_turno",
                    models.CharField(
                        blank=True,
                        help_text="EOL tipo_turno.dc_exibicao_portal — desnormalizado para evitar JOIN.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        help_text="O=Organizada, A=Não Organizada, C=Concluída, E=Extinta.",
                        max_length=1,
                    ),
                ),
                (
                    "codigo_tipo_programa",
                    models.IntegerField(
                        help_text="EOL cd_tipo_programa — FK lógica para tipo_programa."
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[("PAP", "PAP"), ("PAEE", "PAEE")],
                        help_text="'PAP' ou 'PAEE' — desnormalizado de TipoPrograma para filtros diretos.",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Última atualização pelo ETL — usado no incremental.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "turma de programa",
                "verbose_name_plural": "turmas de programa",
                "db_table": "turma_programa",
                "indexes": [
                    models.Index(fields=["ano_letivo"], name="idx_turma_prog_ano"),
                    models.Index(fields=["codigo_ue"], name="idx_turma_prog_ue"),
                    models.Index(fields=["categoria"], name="idx_turma_prog_categoria"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TurmaProgramaComponenteCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_turma",
                    models.BigIntegerField(
                        help_text="FK lógica → turma_programa.codigo_turma."
                    ),
                ),
                (
                    "codigo_componente_curricular",
                    models.BigIntegerField(
                        help_text="FK lógica → componente_curricular_programa.codigo_componente_curricular."
                    ),
                ),
                (
                    "nome_componente_curricular",
                    models.CharField(
                        help_text="EOL dc_componente_curricular — desnormalizado para evitar JOIN.",
                        max_length=200,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "componente curricular da turma",
                "verbose_name_plural": "componentes curriculares das turmas",
                "db_table": "turma_programa_componente_curricular",
                "indexes": [
                    models.Index(
                        fields=["codigo_turma"], name="idx_turma_prog_comp_turma"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codigo_turma", "codigo_componente_curricular"),
                        name="uq_turma_prog_componente",
                    )
                ],
            },
        ),
    ]
