# Generated by Django 5.2.13 on 2026-04-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComponenteCurricularApi",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "codigo_componente",
                    models.IntegerField(
                        help_text="Código do componente no EolConnection — IdComponenteCurricular.",
                        unique=True,
                    ),
                ),
                ("eh_regencia", models.BooleanField(default=False)),
                ("eh_territorio", models.BooleanField(default=False)),
                ("descricao", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "componente curricular (API)",
                "verbose_name_plural": "componentes curriculares (API)",
                "db_table": "componente_curricular_api",
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("guid_perfil", models.UUIDField(blank=True, null=True)),
                ("id_abrangencia", models.IntegerField(blank=True, null=True)),
                ("eh_perfil_manual", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "grupo",
                "verbose_name_plural": "grupos",
                "db_table": "grupo",
            },
        ),
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "nome",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False
                    ),
                ),
                ("valor", models.TextField()),
            ],
            options={
                "verbose_name": "parâmetro",
                "verbose_name_plural": "parâmetros",
                "db_table": "parametro",
            },
        ),
        migrations.CreateModel(
            name="RegenciaComponenteCurricular",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_componente",
                    models.IntegerField(
                        help_text="Ref. ComponenteCurricularApi.codigo_componente."
                    ),
                ),
                ("turno", models.IntegerField(blank=True, null=True)),
                ("ano", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "regência de componente curricular",
                "verbose_name_plural": "regências de componentes curriculares",
                "db_table": "regencia_componente_curricular",
            },
        ),
        migrations.CreateModel(
            name="TurmaTipoItinerario",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=200)),
                (
                    "serie",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "tipo de itinerário de turma",
                "verbose_name_plural": "tipos de itinerários de turmas",
                "db_table": "turma_tipo_itinerario",
            },
        ),
        migrations.CreateModel(
            name="AgrupamentoAtribuicaoTerritorioSaber",
            fields=[
                (
                    "codigo_agrupamento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_territorio_saber",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "codigo_experiencia_pedagogica",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "dt_inicio_atribuicao",
                    models.DateField(blank=True, null=True),
                ),
                ("ano_atribuicao", models.IntegerField(blank=True, null=True)),
                ("dt_fim_atribuicao", models.DateField(blank=True, null=True)),
                ("dt_fim_turma", models.DateField(blank=True, null=True)),
                (
                    "rf_professor",
                    models.CharField(
                        blank=True,
                        help_text="RF do professor — ref. PROFESSORES_DB.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "codigo_turma",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Código da turma — ref. PEDAGOGICO_DB.",
                        null=True,
                    ),
                ),
                (
                    "codigos_componentes_curriculares",
                    models.TextField(
                        blank=True,
                        help_text="Lista de códigos separados por vírgula.",
                        null=True,
                    ),
                ),
                ("ano_letivo", models.IntegerField(blank=True, null=True)),
                (
                    "codigo_motivo_disponibilizacao",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "descricao_territorio_saber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "descricao_experiencia_pedagogica",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "encerramento_atribuicao_agrupamento_atualizado",
                    models.BooleanField(blank=True, null=True),
                ),
                ("criado_em", models.DateTimeField(blank=True, null=True)),
                ("alterado_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "agrupamento de atribuição TdS",
                "verbose_name_plural": "agrupamentos de atribuições TdS",
                "db_table": "agrupamento_atribuicao_territorio_saber",
                "indexes": [
                    models.Index(
                        fields=["rf_professor"], name="prog_idx_aats_professor"
                    ),
                    models.Index(
                        fields=["codigo_turma"], name="prog_idx_aats_turma"
                    ),
                    models.Index(
                        fields=["ano_letivo"], name="prog_idx_aats_ano"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComponenteCurricularPai",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "codigo_componente_pai",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "vigencia",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "componente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relacoes_pai",
                        to="programas.componentecurricularapi",
                        to_field="codigo_componente",
                    ),
                ),
            ],
            options={
                "verbose_name": "componente curricular pai",
                "verbose_name_plural": "componentes curriculares pai",
                "db_table": "componente_curricular_pai",
            },
        ),
        migrations.CreateModel(
            name="ComponenteCurricularPap",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "componente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pap",
                        to="programas.componentecurricularapi",
                        to_field="codigo_componente",
                    ),
                ),
            ],
            options={
                "verbose_name": "componente curricular PAP",
                "verbose_name_plural": "componentes curriculares PAP",
                "db_table": "componente_curricular_pap",
            },
        ),
        migrations.CreateModel(
            name="GrupoCargo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_cargo",
                    models.IntegerField(
                        help_text="Código do cargo — ref. PROFESSORES_DB."
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos",
                        to="programas.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "cargo do grupo",
                "verbose_name_plural": "cargos dos grupos",
                "db_table": "grupo_cargo",
            },
        ),
        migrations.CreateModel(
            name="GrupoFuncaoAtividade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo_tipo_funcao_atividade", models.IntegerField()),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcoes_atividade",
                        to="programas.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "função de atividade do grupo",
                "verbose_name_plural": "funções de atividade dos grupos",
                "db_table": "grupo_funcao_atividade",
            },
        ),
    ]
