# Generated by Django 5.2.14 on 2026-05-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0005_alunopapanoletivo_alunopapanoletivohistorico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matriculaturmaprogramahistorico",
            name="categoria",
            field=models.CharField(
                choices=[("PAP", "PAP"), ("PAEE", "PAEE")],
                help_text="'PAP' ou 'PAEE' — desnormalizado da turma para filtros diretos.",
                max_length=10,
            ),
        ),
    ]
