# Generated by Django 5.2.17 on 2026-09-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0008_categoria_outros"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentecurricularprograma",
            name="vigente",
            field=models.BooleanField(
                help_text="True = componente ativo; False = legado."
            ),
        ),
    ]
