# Generated by Django 5.2.12 on 2026-04-02 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DRE",
            fields=[
                (
                    "codigo_dre",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=20, null=True)),
                ("tipo_unidade_adm", models.IntegerField(blank=True, null=True)),
                (
                    "descricao_unidade_adm",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name": "diretoria regional de educação",
                "verbose_name_plural": "diretorias regionais de educação",
                "db_table": "dre",
            },
        ),
        migrations.CreateModel(
            name="SubPrefeitura",
            fields=[
                (
                    "codigo_sub_prefeitura",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sigla", models.CharField(blank=True, max_length=20, null=True)),
                ("nome", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "sub-prefeitura",
                "verbose_name_plural": "sub-prefeituras",
                "db_table": "sub_prefeitura",
            },
        ),
        migrations.CreateModel(
            name="TipoEscola",
            fields=[
                (
                    "codigo_tipo_escola",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("sigla", models.CharField(blank=True, max_length=20, null=True)),
                ("descricao", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "tipo de escola",
                "verbose_name_plural": "tipos de escola",
                "db_table": "tipo_escola",
            },
        ),
        migrations.CreateModel(
            name="UnidadeEducacional",
            fields=[
                (
                    "codigo_ue",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "nome_nao_oficial",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tipo_ue", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "tipo_logradouro",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("logradouro", models.CharField(blank=True, max_length=200, null=True)),
                ("numero", models.CharField(blank=True, max_length=20, null=True)),
                ("bairro", models.CharField(blank=True, max_length=100, null=True)),
                ("cep", models.CharField(blank=True, max_length=10, null=True)),
                ("municipio", models.CharField(blank=True, max_length=100, null=True)),
                ("distrito", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("telefone_1", models.CharField(blank=True, max_length=50, null=True)),
                ("telefone_2", models.CharField(blank=True, max_length=50, null=True)),
                ("ano_construcao", models.IntegerField(blank=True, null=True)),
                (
                    "propriedade",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("organizacao_parceira", models.BooleanField(default=False)),
                ("vagas_matutino", models.IntegerField(default=0)),
                ("vagas_vespertino", models.IntegerField(default=0)),
                ("vagas_noturno", models.IntegerField(default=0)),
                ("vagas_intermediario", models.IntegerField(default=0)),
                ("vagas_integral", models.IntegerField(default=0)),
                ("vagas_total", models.IntegerField(default=0)),
                ("quantidade_funcionarios", models.IntegerField(default=0)),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "codigo_ue_integracao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "dre",
                    models.ForeignKey(
                        db_column="codigo_dre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades",
                        to="institucional.dre",
                    ),
                ),
                (
                    "subprefeitura",
                    models.ForeignKey(
                        blank=True,
                        db_column="codigo_sub_prefeitura",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unidades",
                        to="institucional.subprefeitura",
                    ),
                ),
                (
                    "tipo_escola",
                    models.ForeignKey(
                        blank=True,
                        db_column="codigo_tipo_escola",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unidades",
                        to="institucional.tipoescola",
                    ),
                ),
            ],
            options={
                "verbose_name": "unidade educacional",
                "verbose_name_plural": "unidades educacionais",
                "db_table": "unidade_educacional",
                "indexes": [
                    models.Index(fields=["dre"], name="idx_ue_dre"),
                    models.Index(fields=["tipo_escola"], name="idx_ue_tipo_escola"),
                    models.Index(fields=["subprefeitura"], name="idx_ue_subprefeitura"),
                ],
            },
        ),
    ]
