# Generated by Django 5.2.14 on 2026-05-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "institucional",
            "0002_tipo_escola_data_atualizacao_ue_eh_ceu_data_atualizacao",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadeeducacional",
            name="codigo_logradouro",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadeeducacional",
            name="codigo_tp_equipamento",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
