# Generated by Django 5.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institucional", "0005_alter_dre_sigla_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DREAbrangencia",
            fields=[
                (
                    "codigo_dre",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "abreviacao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "DRE de abrangência",
                "verbose_name_plural": "DREs de abrangência",
                "db_table": "dre_abrangencia",
            },
        ),
    ]
