# Generated by Django 5.2.12 on 2026-03-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_auditoria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtlAuditoriaLinha",
            fields=[
                (
                    "id_destino",
                    models.CharField(
                        help_text="Chave composta '{tabela_destino}:{id_origem}'",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hash_controle",
                    models.CharField(
                        help_text="SHA-256 hex dos dados relevantes da linha de origem.",
                        max_length=64,
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "etl_auditoria_linha",
                "indexes": [
                    models.Index(fields=["atualizado_em"], name="idx_eal_atualizado")
                ],
            },
        ),
    ]
