# Generated by Django 5.2.12 on 2026-03-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escolas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultaescolaslog",
            options={
                "verbose_name": "consulta de escolas",
                "verbose_name_plural": "consultas de escolas",
            },
        ),
    ]
