# Generated by Django 5.2.12 on 2026-03-31 00:33

import django.db.models.deletion
from django.db import migrations, models

HELP_TEXT_UNIDADE_EDUCACIONAL_ID = "ID da UnidadeEducacional neste DB."
HELP_TEXT_SERIE_TURMA_GRADE_ID = "ID da SerieTurmaGrade neste DB."
HELP_TEXT_TURMA_ESCOLA_ID = "ID da TurmaEscola neste DB."


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="CargoBaseServidor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_cargo",
                    models.IntegerField(
                        help_text="ID do cargo — ref. domínio RH/funcional."
                    ),
                ),
                ("dt_posse", models.DateField(blank=True, null=True)),
                ("dt_fim_nomeacao", models.DateField(blank=True, null=True)),
                ("dt_cancelamento", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "cargo base do servidor",
                "verbose_name_plural": "cargos base dos servidores",
                "db_table": "cargo_base_servidor",
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "codigo_pessoa",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("nome", models.CharField(max_length=200)),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "pessoas",
                "db_table": "pessoa",
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "codigo_rf",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name": "professor",
                "verbose_name_plural": "professores",
                "db_table": "professor",
            },
        ),
        migrations.CreateModel(
            name="AgrupamentoAtribuicaoTerritorioSaber",
            fields=[
                (
                    "codigo_agrupamento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_territorio_saber",
                    models.IntegerField(
                        blank=True,
                        help_text="ID do território do saber — ref. domínio pedagógico.",
                        null=True,
                    ),
                ),
                (
                    "codigo_experiencia_pedagogica",
                    models.IntegerField(
                        blank=True,
                        help_text="ID da experiência pedagógica — ref. domínio pedagógico.",
                        null=True,
                    ),
                ),
                (
                    "dt_inicio_atribuicao",
                    models.DateField(blank=True, null=True),
                ),
                ("ano_atribuicao", models.IntegerField(blank=True, null=True)),
                ("dt_fim_atribuicao", models.DateField(blank=True, null=True)),
                ("dt_fim_turma", models.DateField(blank=True, null=True)),
                (
                    "rf_professor",
                    models.CharField(
                        blank=True,
                        help_text="Ref. Professor.codigo_rf neste DB.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "codigo_turma",
                    models.BigIntegerField(
                        blank=True,
                        help_text=HELP_TEXT_TURMA_ESCOLA_ID,
                        null=True,
                    ),
                ),
                (
                    "codigos_componentes_curriculares",
                    models.TextField(
                        blank=True,
                        help_text="Lista de IDs de componentes separados por vírgula.",
                        null=True,
                    ),
                ),
                ("ano_letivo", models.IntegerField(blank=True, null=True)),
                (
                    "codigo_motivo_disponibilizacao",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "encerramento_atribuicao_agrupamento_atualizado",
                    models.BooleanField(blank=True, null=True),
                ),
                ("criado_em", models.DateTimeField(blank=True, null=True)),
                ("alterado_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "agrupamento de atribuição TdS",
                "verbose_name_plural": "agrupamentos de atribuições TdS",
                "db_table": "agrupamento_atribuicao_territorio_saber",
                "indexes": [
                    models.Index(
                        fields=["rf_professor"], name="prof_idx_aats_professor"
                    ),
                    models.Index(
                        fields=["codigo_turma"], name="prof_idx_aats_turma"
                    ),
                    models.Index(
                        fields=["ano_letivo"], name="prof_idx_aats_ano"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FuncaoAtividadeCargoServidor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_unidade_local_servico",
                    models.CharField(
                        help_text="ID da UE onde a função é exercida.",
                        max_length=20,
                    ),
                ),
                (
                    "dt_fim_funcao_atividade",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "cargo_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcoes_atividade",
                        to="professores.cargobaseservidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "função de atividade do cargo do servidor",
                "verbose_name_plural": "funções de atividade dos cargos dos servidores",
                "db_table": "funcao_atividade_cargo_servidor",
            },
        ),
        migrations.CreateModel(
            name="LaudoMedico",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cargo_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laudos_medicos",
                        to="professores.cargobaseservidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "laudo médico",
                "verbose_name_plural": "laudos médicos",
                "db_table": "laudo_medico",
            },
        ),
        migrations.CreateModel(
            name="ContratoExterno",
            fields=[
                (
                    "codigo_contrato",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_tipo_funcao",
                    models.IntegerField(
                        help_text="ID do tipo de função do funcionário externo."
                    ),
                ),
                (
                    "codigo_unidade_educacao",
                    models.CharField(
                        help_text="HELP_TEXT_UNIDADE_EDUCACIONAL_ID",
                        max_length=20,
                    ),
                ),
                ("dt_cancelamento", models.DateField(blank=True, null=True)),
                (
                    "codigo_motivo_desligamento",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="professores.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrato externo",
                "verbose_name_plural": "contratos externos",
                "db_table": "contrato_externo",
            },
        ),
        migrations.AddField(
            model_name="cargobaseservidor",
            name="professor",
            field=models.ForeignKey(
                db_column="codigo_rf",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargos_base",
                to="professores.professor",
            ),
        ),
        migrations.CreateModel(
            name="SerieTurmaGrade",
            fields=[
                (
                    "codigo_serie_grade",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_turma",
                    models.BigIntegerField(
                        help_text=HELP_TEXT_TURMA_ESCOLA_ID
                    ),
                ),
                (
                    "codigo_escola",
                    models.CharField(
                        help_text="HELP_TEXT_UNIDADE_EDUCACIONAL_ID",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_escola_grade",
                    models.IntegerField(
                        help_text="ID da escola_grade — ref. domínio pedagógico."
                    ),
                ),
                ("dt_fim", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "série-grade da turma",
                "verbose_name_plural": "séries-grade das turmas",
                "db_table": "serie_turma_grade",
                "indexes": [
                    models.Index(
                        fields=["codigo_turma"], name="prof_idx_stg_turma"
                    ),
                    models.Index(
                        fields=["dt_fim"], name="prof_idx_stg_dt_fim"
                    ),
                    models.Index(
                        fields=["codigo_escola"], name="prof_idx_stg_escola"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TurmaEscola",
            fields=[
                (
                    "codigo_turma",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_escola",
                    models.CharField(
                        help_text="HELP_TEXT_UNIDADE_EDUCACIONAL_ID",
                        max_length=20,
                    ),
                ),
                ("ano_letivo", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        help_text="'O'=Aberta, 'A'=Ativa, 'E'=Extinta, 'C'=Cancelada.",
                        max_length=1,
                    ),
                ),
                ("dt_fim_turma", models.DateField(blank=True, null=True)),
                ("dt_fim", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "turma escolar",
                "verbose_name_plural": "turmas escolares",
                "db_table": "turma_escola",
                "indexes": [
                    models.Index(
                        fields=["codigo_escola"], name="prof_idx_te_escola"
                    ),
                    models.Index(
                        fields=["ano_letivo"], name="prof_idx_te_ano"
                    ),
                    models.Index(fields=["status"], name="prof_idx_te_status"),
                    models.Index(
                        fields=["codigo_escola", "ano_letivo"],
                        name="prof_idx_te_escola_ano",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TurmaEscolaGradePrograma",
            fields=[
                (
                    "codigo",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_turma",
                    models.BigIntegerField(
                        help_text=HELP_TEXT_TURMA_ESCOLA_ID
                    ),
                ),
                (
                    "codigo_escola_grade",
                    models.IntegerField(
                        help_text="ID da escola_grade — ref. domínio pedagógico."
                    ),
                ),
                ("dt_fim", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "grade/programa da turma",
                "verbose_name_plural": "grades/programas das turmas",
                "db_table": "turma_escola_grade_programa",
                "indexes": [
                    models.Index(
                        fields=["codigo_turma"], name="prof_idx_tegp_turma"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TurmaGradeTerritorioExperiencia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_serie_grade",
                    models.IntegerField(
                        help_text="HELP_TEXT_SERIE_TURMA_GRADE_ID"
                    ),
                ),
                (
                    "codigo_componente_curricular",
                    models.IntegerField(
                        help_text="ID do componente curricular — ref. domínio curricular."
                    ),
                ),
                (
                    "codigo_territorio_saber",
                    models.IntegerField(
                        help_text="ID do território do saber — ref. domínio pedagógico."
                    ),
                ),
                (
                    "codigo_experiencia_pedagogica",
                    models.IntegerField(
                        help_text="ID da experiência pedagógica — ref. domínio pedagógico."
                    ),
                ),
                ("dt_inicio", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "território/experiência da grade de turma",
                "verbose_name_plural": "territórios/experiências das grades de turmas",
                "db_table": "turma_grade_territorio_experiencia",
                "indexes": [
                    models.Index(
                        fields=["codigo_serie_grade"],
                        name="prof_idx_tgte_serie_grade",
                    ),
                    models.Index(
                        fields=["codigo_componente_curricular"],
                        name="prof_idx_tgte_componente",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnidadeEducacional",
            fields=[
                (
                    "codigo_ue",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False
                    ),
                ),
                (
                    "codigo_dre",
                    models.CharField(
                        blank=True,
                        help_text="ID da DRE — ref. domínio institucional.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "codigo_tipo_escola",
                    models.IntegerField(
                        blank=True,
                        help_text="ID do tipo de escola — usado em filtros tp_escola IN @tiposEscola.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "unidade educacional",
                "verbose_name_plural": "unidades educacionais",
                "db_table": "unidade_educacional",
                "indexes": [
                    models.Index(
                        fields=["codigo_dre"], name="prof_idx_ue_dre"
                    ),
                    models.Index(
                        fields=["codigo_tipo_escola"],
                        name="prof_idx_ue_tipo_escola",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AtribuicaoAula",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_unidade_educacao",
                    models.CharField(
                        help_text="HELP_TEXT_UNIDADE_EDUCACIONAL_ID",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_turma_escola",
                    models.BigIntegerField(
                        blank=True,
                        help_text=HELP_TEXT_TURMA_ESCOLA_ID,
                        null=True,
                    ),
                ),
                (
                    "codigo_turma_escola_grade_programa",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID da TurmaEscolaGradePrograma neste DB.",
                        null=True,
                    ),
                ),
                (
                    "codigo_grade",
                    models.IntegerField(
                        help_text="ID da grade — ref. domínio pedagógico."
                    ),
                ),
                (
                    "codigo_componente_curricular",
                    models.IntegerField(
                        help_text="ID do componente curricular — ref. domínio curricular."
                    ),
                ),
                (
                    "codigo_serie_grade",
                    models.IntegerField(
                        help_text="HELP_TEXT_SERIE_TURMA_GRADE_ID"
                    ),
                ),
                ("ano_atribuicao", models.IntegerField()),
                ("dt_atribuicao_aula", models.DateField()),
                (
                    "dt_disponibilizacao_aulas",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "codigo_motivo_disponibilizacao",
                    models.IntegerField(blank=True, null=True),
                ),
                ("dt_cancelamento", models.DateField(blank=True, null=True)),
                (
                    "cargo_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atribuicoes",
                        to="professores.cargobaseservidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "atribuição de aula",
                "verbose_name_plural": "atribuições de aulas",
                "db_table": "atribuicao_aula",
                "indexes": [
                    models.Index(
                        fields=["codigo_unidade_educacao"], name="idx_aa_ue"
                    ),
                    models.Index(
                        fields=["codigo_turma_escola"], name="idx_aa_turma"
                    ),
                    models.Index(
                        fields=["codigo_componente_curricular"],
                        name="idx_aa_componente",
                    ),
                    models.Index(fields=["ano_atribuicao"], name="idx_aa_ano"),
                    models.Index(
                        fields=["dt_cancelamento"], name="idx_aa_cancelamento"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CargoSobrepostoServidor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_cargo",
                    models.IntegerField(
                        help_text="ID do cargo sobreposto — ref. domínio RH/funcional."
                    ),
                ),
                (
                    "codigo_unidade_local_servico",
                    models.CharField(
                        help_text="ID da UE onde o cargo sobreposto é exercido.",
                        max_length=20,
                    ),
                ),
                (
                    "dt_fim_cargo_sobreposto",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "cargo_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos_sobrepostos",
                        to="professores.cargobaseservidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "cargo sobreposto do servidor",
                "verbose_name_plural": "cargos sobrepostos dos servidores",
                "db_table": "cargo_sobreposto_servidor",
                "indexes": [
                    models.Index(
                        fields=["dt_fim_cargo_sobreposto"],
                        name="idx_css_dt_fim",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AtribuicaoExterno",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_unidade_educacao",
                    models.CharField(
                        help_text="HELP_TEXT_UNIDADE_EDUCACIONAL_ID",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_grade",
                    models.IntegerField(
                        help_text="ID da grade — ref. domínio pedagógico."
                    ),
                ),
                (
                    "codigo_componente_curricular",
                    models.IntegerField(
                        help_text="ID do componente curricular — ref. domínio curricular."
                    ),
                ),
                (
                    "codigo_serie_grade",
                    models.IntegerField(
                        help_text="HELP_TEXT_SERIE_TURMA_GRADE_ID"
                    ),
                ),
                (
                    "codigo_turma_escola_grade_programa",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID da TurmaEscolaGradePrograma neste DB.",
                        null=True,
                    ),
                ),
                ("ano_atribuicao", models.IntegerField()),
                ("dt_atribuicao", models.DateField()),
                (
                    "dt_disponibilizacao",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "codigo_motivo_disponibilizacao_externo",
                    models.IntegerField(blank=True, null=True),
                ),
                ("dt_cancelamento", models.DateField(blank=True, null=True)),
                (
                    "contrato_externo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atribuicoes",
                        to="professores.contratoexterno",
                    ),
                ),
            ],
            options={
                "verbose_name": "atribuição de professor externo",
                "verbose_name_plural": "atribuições de professores externos",
                "db_table": "atribuicao_externo",
                "indexes": [
                    models.Index(
                        fields=["codigo_unidade_educacao"], name="idx_ae_ue"
                    ),
                    models.Index(
                        fields=["codigo_componente_curricular"],
                        name="idx_ae_componente",
                    ),
                    models.Index(fields=["ano_atribuicao"], name="idx_ae_ano"),
                    models.Index(
                        fields=["dt_cancelamento"], name="idx_ae_cancelamento"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LotacaoServidor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_unidade_educacao",
                    models.CharField(
                        help_text="HELP_TEXT_UNIDADE_EDUCACIONAL_ID",
                        max_length=20,
                    ),
                ),
                ("dt_inicio", models.DateField(blank=True, null=True)),
                ("dt_fim", models.DateField(blank=True, null=True)),
                (
                    "cargo_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotacoes",
                        to="professores.cargobaseservidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "lotação do servidor",
                "verbose_name_plural": "lotações dos servidores",
                "db_table": "lotacao_servidor",
                "indexes": [
                    models.Index(
                        fields=["codigo_unidade_educacao"], name="idx_ls_ue"
                    ),
                    models.Index(fields=["dt_fim"], name="idx_ls_dt_fim"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contratoexterno",
            index=models.Index(
                fields=["codigo_unidade_educacao"], name="idx_ce_ue"
            ),
        ),
        migrations.AddIndex(
            model_name="contratoexterno",
            index=models.Index(
                fields=["dt_cancelamento"], name="idx_ce_cancelamento"
            ),
        ),
        migrations.AddIndex(
            model_name="cargobaseservidor",
            index=models.Index(fields=["professor"], name="idx_cbs_professor"),
        ),
        migrations.AddIndex(
            model_name="cargobaseservidor",
            index=models.Index(fields=["codigo_cargo"], name="idx_cbs_cargo"),
        ),
        migrations.AddIndex(
            model_name="cargobaseservidor",
            index=models.Index(
                fields=["dt_fim_nomeacao"], name="idx_cbs_fim_nomeacao"
            ),
        ),
    ]
