# Generated by Django 5.2.12 on 2026-03-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "codigo_cargo",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "cargo",
                "verbose_name_plural": "cargos",
                "db_table": "cargo",
            },
        ),
        migrations.CreateModel(
            name="DRE",
            fields=[
                (
                    "codigo_dre",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "diretoria regional de educação",
                "verbose_name_plural": "diretorias regionais de educação",
                "db_table": "dre",
            },
        ),
        migrations.CreateModel(
            name="FuncaoFuncionarioExterno",
            fields=[
                (
                    "codigo_tipo_funcao",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("dt_cancelamento", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "função de funcionário externo",
                "verbose_name_plural": "funções de funcionários externos",
                "db_table": "funcao_funcionario_externo",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "codigo_grade",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_serie_ensino",
                    models.IntegerField(
                        help_text="Ref. SerieEnsino.codigo_serie neste DB."
                    ),
                ),
                ("codigo_tipo_turno", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "grade curricular",
                "verbose_name_plural": "grades curriculares",
                "db_table": "grade",
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "codigo_pessoa",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("nome", models.CharField(max_length=200)),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "pessoas",
                "db_table": "pessoa",
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "codigo_rf",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name": "professor",
                "verbose_name_plural": "professores",
                "db_table": "professor",
            },
        ),
        migrations.CreateModel(
            name="SerieEnsino",
            fields=[
                (
                    "codigo_serie",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "sigla_resumida",
                    models.CharField(
                        blank=True,
                        help_text="sg_resumida_serie — exibida como AnoTurma nas queries.",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "série de ensino",
                "verbose_name_plural": "séries de ensino",
                "db_table": "serie_ensino",
            },
        ),
        migrations.CreateModel(
            name="TerritorioSaber",
            fields=[
                (
                    "codigo_territorio",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "território do saber",
                "verbose_name_plural": "territórios do saber",
                "db_table": "territorio_saber",
            },
        ),
        migrations.CreateModel(
            name="TipoEscola",
            fields=[
                (
                    "codigo_tipo_escola",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "tipo de escola",
                "verbose_name_plural": "tipos de escola",
                "db_table": "tipo_escola",
            },
        ),
        migrations.CreateModel(
            name="TipoExperienciaPedagogica",
            fields=[
                (
                    "codigo_experiencia",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "tipo de experiência pedagógica",
                "verbose_name_plural": "tipos de experiências pedagógicas",
                "db_table": "tipo_experiencia_pedagogica",
            },
        ),
        migrations.CreateModel(
            name="AgrupamentoAtribuicaoTerritorioSaber",
            fields=[
                (
                    "codigo_agrupamento",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("codigo_territorio_saber", models.IntegerField(blank=True, null=True)),
                (
                    "codigo_experiencia_pedagogica",
                    models.IntegerField(blank=True, null=True),
                ),
                ("dt_inicio_atribuicao", models.DateField(blank=True, null=True)),
                ("ano_atribuicao", models.IntegerField(blank=True, null=True)),
                ("dt_fim_atribuicao", models.DateField(blank=True, null=True)),
                ("dt_fim_turma", models.DateField(blank=True, null=True)),
                (
                    "rf_professor",
                    models.CharField(
                        blank=True,
                        help_text="Ref. Professor.codigo_rf neste DB.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "codigo_turma",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Ref. TurmaEscola.codigo_turma neste DB.",
                        null=True,
                    ),
                ),
                (
                    "codigos_componentes_curriculares",
                    models.TextField(
                        blank=True,
                        help_text="Lista de códigos separados por vírgula.",
                        null=True,
                    ),
                ),
                ("ano_letivo", models.IntegerField(blank=True, null=True)),
                (
                    "codigo_motivo_disponibilizacao",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "descricao_territorio_saber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "descricao_experiencia_pedagogica",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "encerramento_atribuicao_agrupamento_atualizado",
                    models.BooleanField(blank=True, null=True),
                ),
                ("criado_em", models.DateTimeField(blank=True, null=True)),
                ("alterado_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "agrupamento de atribuição TdS",
                "verbose_name_plural": "agrupamentos de atribuições TdS",
                "db_table": "agrupamento_atribuicao_territorio_saber",
                "indexes": [
                    models.Index(
                        fields=["rf_professor"], name="prof_idx_aats_professor"
                    ),
                    models.Index(fields=["codigo_turma"], name="prof_idx_aats_turma"),
                    models.Index(fields=["ano_letivo"], name="prof_idx_aats_ano"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CargoBaseServidor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dt_posse", models.DateField(blank=True, null=True)),
                ("dt_fim_nomeacao", models.DateField(blank=True, null=True)),
                ("dt_cancelamento", models.DateField(blank=True, null=True)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servidores",
                        to="professores.cargo",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        db_column="codigo_rf",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos_base",
                        to="professores.professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "cargo base do servidor",
                "verbose_name_plural": "cargos base dos servidores",
                "db_table": "cargo_base_servidor",
            },
        ),
        migrations.CreateModel(
            name="ComponenteCurricular",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=200)),
                ("dt_cancelamento", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "componente curricular",
                "verbose_name_plural": "componentes curriculares",
                "db_table": "componente_curricular",
                "indexes": [
                    models.Index(fields=["dt_cancelamento"], name="idx_cc_cancelamento")
                ],
            },
        ),
        migrations.CreateModel(
            name="FuncaoAtividadeCargoServidor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_unidade_local_servico",
                    models.CharField(
                        help_text="UE onde a função é exercida.", max_length=20
                    ),
                ),
                ("dt_fim_funcao_atividade", models.DateField(blank=True, null=True)),
                (
                    "cargo_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcoes_atividade",
                        to="professores.cargobaseservidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "função de atividade do cargo do servidor",
                "verbose_name_plural": "funções de atividade dos cargos dos servidores",
                "db_table": "funcao_atividade_cargo_servidor",
            },
        ),
        migrations.CreateModel(
            name="EscolaGrade",
            fields=[
                (
                    "codigo_escola_grade",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_escola",
                    models.CharField(
                        help_text="Ref. UnidadeEducacional.codigo_ue neste DB.",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        db_column="codigo_grade",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escola_grades",
                        to="professores.grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "grade da escola",
                "verbose_name_plural": "grades das escolas",
                "db_table": "escola_grade",
            },
        ),
        migrations.CreateModel(
            name="LaudoMedico",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cargo_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laudos_medicos",
                        to="professores.cargobaseservidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "laudo médico",
                "verbose_name_plural": "laudos médicos",
                "db_table": "laudo_medico",
            },
        ),
        migrations.CreateModel(
            name="LotacaoServidor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_unidade_educacao",
                    models.CharField(
                        help_text="Ref. UnidadeEducacional.codigo_ue neste DB.",
                        max_length=20,
                    ),
                ),
                ("dt_inicio", models.DateField(blank=True, null=True)),
                ("dt_fim", models.DateField(blank=True, null=True)),
                (
                    "cargo_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotacoes",
                        to="professores.cargobaseservidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "lotação do servidor",
                "verbose_name_plural": "lotações dos servidores",
                "db_table": "lotacao_servidor",
            },
        ),
        migrations.CreateModel(
            name="ContratoExterno",
            fields=[
                (
                    "codigo_contrato",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_unidade_educacao",
                    models.CharField(
                        help_text="Ref. UnidadeEducacional.codigo_ue neste DB.",
                        max_length=20,
                    ),
                ),
                ("dt_cancelamento", models.DateField(blank=True, null=True)),
                (
                    "codigo_motivo_desligamento",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tipo_funcao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="professores.funcaofuncionarioexterno",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="professores.pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrato externo",
                "verbose_name_plural": "contratos externos",
                "db_table": "contrato_externo",
            },
        ),
        migrations.CreateModel(
            name="TurmaEscola",
            fields=[
                (
                    "codigo_turma",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_escola",
                    models.CharField(
                        help_text="Ref. UnidadeEducacional.codigo_ue neste DB.",
                        max_length=20,
                    ),
                ),
                ("ano_letivo", models.IntegerField()),
                ("nome_turma", models.CharField(max_length=200)),
                (
                    "codigo_tipo_turma",
                    models.IntegerField(help_text="1=Regular, 3=Programa."),
                ),
                ("codigo_duracao", models.IntegerField(blank=True, null=True)),
                ("codigo_tipo_turno", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        help_text="'O'=Aberta, 'A'=Ativa, 'E'=Extinta, 'C'=Cancelada.",
                        max_length=1,
                    ),
                ),
                ("dt_inicio_turma", models.DateField(blank=True, null=True)),
                ("dt_fim_turma", models.DateField(blank=True, null=True)),
                ("dt_fim", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "turma escolar",
                "verbose_name_plural": "turmas escolares",
                "db_table": "turma_escola",
                "indexes": [
                    models.Index(fields=["codigo_escola"], name="prof_idx_te_escola"),
                    models.Index(fields=["ano_letivo"], name="prof_idx_te_ano"),
                    models.Index(fields=["status"], name="prof_idx_te_status"),
                    models.Index(
                        fields=["codigo_escola", "ano_letivo"],
                        name="prof_idx_te_escola_ano",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SerieTurmaGrade",
            fields=[
                (
                    "codigo_serie_grade",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "codigo_escola",
                    models.CharField(
                        help_text="Ref. UnidadeEducacional.codigo_ue neste DB.",
                        max_length=20,
                    ),
                ),
                ("dt_fim", models.DateField(blank=True, null=True)),
                (
                    "escola_grade",
                    models.ForeignKey(
                        blank=True,
                        db_column="codigo_escola_grade",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="serie_turma_grades",
                        to="professores.escolagrade",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        db_column="codigo_turma",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serie_grades",
                        to="professores.turmaescola",
                    ),
                ),
            ],
            options={
                "verbose_name": "série-grade da turma",
                "verbose_name_plural": "séries-grade das turmas",
                "db_table": "serie_turma_grade",
            },
        ),
        migrations.CreateModel(
            name="TurmaEscolaGradePrograma",
            fields=[
                ("codigo", models.BigIntegerField(primary_key=True, serialize=False)),
                ("dt_fim", models.DateField(blank=True, null=True)),
                (
                    "escola_grade",
                    models.ForeignKey(
                        db_column="codigo_escola_grade",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turma_programas",
                        to="professores.escolagrade",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        db_column="codigo_turma",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_programas",
                        to="professores.turmaescola",
                    ),
                ),
            ],
            options={
                "verbose_name": "grade/programa da turma",
                "verbose_name_plural": "grades/programas das turmas",
                "db_table": "turma_escola_grade_programa",
            },
        ),
        migrations.CreateModel(
            name="TurmaGradeTerritorioExperiencia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_componente_curricular",
                    models.IntegerField(
                        help_text="Ref. ComponenteCurricular.codigo neste DB."
                    ),
                ),
                ("dt_inicio", models.DateField(blank=True, null=True)),
                (
                    "experiencia_pedagogica",
                    models.ForeignKey(
                        db_column="codigo_experiencia",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_experiencias",
                        to="professores.tipoexperienciapedagogica",
                    ),
                ),
                (
                    "serie_grade",
                    models.ForeignKey(
                        db_column="codigo_serie_grade",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="territorios_experiencias",
                        to="professores.serieturmagrade",
                    ),
                ),
                (
                    "territorio_saber",
                    models.ForeignKey(
                        db_column="codigo_territorio",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_territorios",
                        to="professores.territoriosaber",
                    ),
                ),
            ],
            options={
                "verbose_name": "território/experiência da grade de turma",
                "verbose_name_plural": "territórios/experiências das grades de turmas",
                "db_table": "turma_grade_territorio_experiencia",
            },
        ),
        migrations.CreateModel(
            name="UnidadeEducacional",
            fields=[
                (
                    "codigo_ue",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=50, null=True)),
                ("nome_dre", models.CharField(max_length=200)),
                ("sigla_dre", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "sigla_tipo_escola",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "dre",
                    models.ForeignKey(
                        db_column="codigo_dre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades",
                        to="professores.dre",
                    ),
                ),
                (
                    "tipo_escola",
                    models.ForeignKey(
                        blank=True,
                        db_column="codigo_tipo_escola",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unidades",
                        to="professores.tipoescola",
                    ),
                ),
            ],
            options={
                "verbose_name": "unidade educacional",
                "verbose_name_plural": "unidades educacionais",
                "db_table": "unidade_educacional",
            },
        ),
        migrations.CreateModel(
            name="AtribuicaoAula",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_unidade_educacao",
                    models.CharField(
                        help_text="Ref. UnidadeEducacional.codigo_ue neste DB.",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_turma_escola",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Ref. TurmaEscola.codigo_turma neste DB.",
                        null=True,
                    ),
                ),
                (
                    "codigo_turma_escola_grade_programa",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Ref. TurmaEscolaGradePrograma.codigo neste DB.",
                        null=True,
                    ),
                ),
                (
                    "codigo_grade",
                    models.IntegerField(help_text="Ref. Grade.codigo_grade neste DB."),
                ),
                (
                    "codigo_componente_curricular",
                    models.IntegerField(
                        help_text="Ref. ComponenteCurricular.codigo neste DB."
                    ),
                ),
                (
                    "codigo_serie_grade",
                    models.IntegerField(
                        help_text="Ref. SerieTurmaGrade.codigo_serie_grade neste DB."
                    ),
                ),
                ("ano_atribuicao", models.IntegerField()),
                ("dt_atribuicao_aula", models.DateField()),
                ("dt_disponibilizacao_aulas", models.DateField(blank=True, null=True)),
                (
                    "codigo_motivo_disponibilizacao",
                    models.IntegerField(blank=True, null=True),
                ),
                ("dt_cancelamento", models.DateField(blank=True, null=True)),
                (
                    "cargo_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atribuicoes",
                        to="professores.cargobaseservidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "atribuição de aula",
                "verbose_name_plural": "atribuições de aulas",
                "db_table": "atribuicao_aula",
                "indexes": [
                    models.Index(fields=["codigo_unidade_educacao"], name="idx_aa_ue"),
                    models.Index(fields=["codigo_turma_escola"], name="idx_aa_turma"),
                    models.Index(
                        fields=["codigo_componente_curricular"],
                        name="idx_aa_componente",
                    ),
                    models.Index(fields=["ano_atribuicao"], name="idx_aa_ano"),
                    models.Index(
                        fields=["dt_cancelamento"], name="idx_aa_cancelamento"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CargoSobrepostoServidor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_unidade_local_servico",
                    models.CharField(
                        help_text="UE onde o cargo sobreposto é exercido.",
                        max_length=20,
                    ),
                ),
                ("dt_fim_cargo_sobreposto", models.DateField(blank=True, null=True)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sobreposicoes",
                        to="professores.cargo",
                    ),
                ),
                (
                    "cargo_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos_sobrepostos",
                        to="professores.cargobaseservidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "cargo sobreposto do servidor",
                "verbose_name_plural": "cargos sobrepostos dos servidores",
                "db_table": "cargo_sobreposto_servidor",
                "indexes": [
                    models.Index(
                        fields=["dt_fim_cargo_sobreposto"], name="idx_css_dt_fim"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AtribuicaoExterno",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_unidade_educacao",
                    models.CharField(
                        help_text="Ref. UnidadeEducacional.codigo_ue neste DB.",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_grade",
                    models.IntegerField(help_text="Ref. Grade.codigo_grade neste DB."),
                ),
                (
                    "codigo_componente_curricular",
                    models.IntegerField(
                        help_text="Ref. ComponenteCurricular.codigo neste DB."
                    ),
                ),
                (
                    "codigo_serie_grade",
                    models.IntegerField(
                        help_text="Ref. SerieTurmaGrade.codigo_serie_grade neste DB."
                    ),
                ),
                (
                    "codigo_turma_escola_grade_programa",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Ref. TurmaEscolaGradePrograma.codigo neste DB.",
                        null=True,
                    ),
                ),
                ("ano_atribuicao", models.IntegerField()),
                ("dt_atribuicao", models.DateField()),
                ("dt_disponibilizacao", models.DateField(blank=True, null=True)),
                (
                    "codigo_motivo_disponibilizacao_externo",
                    models.IntegerField(blank=True, null=True),
                ),
                ("dt_cancelamento", models.DateField(blank=True, null=True)),
                (
                    "contrato_externo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atribuicoes",
                        to="professores.contratoexterno",
                    ),
                ),
            ],
            options={
                "verbose_name": "atribuição de professor externo",
                "verbose_name_plural": "atribuições de professores externos",
                "db_table": "atribuicao_externo",
                "indexes": [
                    models.Index(fields=["codigo_unidade_educacao"], name="idx_ae_ue"),
                    models.Index(
                        fields=["codigo_componente_curricular"],
                        name="idx_ae_componente",
                    ),
                    models.Index(fields=["ano_atribuicao"], name="idx_ae_ano"),
                    models.Index(
                        fields=["dt_cancelamento"], name="idx_ae_cancelamento"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="escolagrade",
            index=models.Index(fields=["codigo_escola"], name="prof_idx_eg_escola"),
        ),
        migrations.AddIndex(
            model_name="lotacaoservidor",
            index=models.Index(fields=["codigo_unidade_educacao"], name="idx_ls_ue"),
        ),
        migrations.AddIndex(
            model_name="lotacaoservidor",
            index=models.Index(fields=["dt_fim"], name="idx_ls_dt_fim"),
        ),
        migrations.AddIndex(
            model_name="contratoexterno",
            index=models.Index(fields=["codigo_unidade_educacao"], name="idx_ce_ue"),
        ),
        migrations.AddIndex(
            model_name="contratoexterno",
            index=models.Index(fields=["dt_cancelamento"], name="idx_ce_cancelamento"),
        ),
        migrations.AddIndex(
            model_name="cargobaseservidor",
            index=models.Index(fields=["professor"], name="idx_cbs_professor"),
        ),
        migrations.AddIndex(
            model_name="cargobaseservidor",
            index=models.Index(fields=["dt_fim_nomeacao"], name="idx_cbs_fim_nomeacao"),
        ),
        migrations.AddIndex(
            model_name="serieturmagrade",
            index=models.Index(fields=["dt_fim"], name="prof_idx_stg_dt_fim"),
        ),
        migrations.AddIndex(
            model_name="serieturmagrade",
            index=models.Index(fields=["codigo_escola"], name="prof_idx_stg_escola"),
        ),
        migrations.AddIndex(
            model_name="turmagradeterritorioexperiencia",
            index=models.Index(
                fields=["codigo_componente_curricular"], name="prof_idx_tgte_componente"
            ),
        ),
        migrations.AddIndex(
            model_name="unidadeeducacional",
            index=models.Index(fields=["dre"], name="prof_idx_ue_dre"),
        ),
        migrations.AddIndex(
            model_name="unidadeeducacional",
            index=models.Index(fields=["tipo_escola"], name="prof_idx_ue_tipo_escola"),
        ),
    ]
