# Generated by Django 5.2.12 on 2026-03-31 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargobaseservidor",
            name="professor",
            field=models.ForeignKey(
                db_column="codigo_rf",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargos_base",
                to="professores.professor",
            ),
        ),
    ]
