# Generated by Django 5.2.12 on 2026-03-31 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professores", "0002_alter_cargobaseservidor_professor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atribuicaoaula",
            name="cargo_base",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atribuicoes",
                to="professores.cargobaseservidor",
            ),
        ),
        migrations.AlterField(
            model_name="atribuicaoexterno",
            name="contrato_externo",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atribuicoes",
                to="professores.contratoexterno",
            ),
        ),
        migrations.AlterField(
            model_name="cargosobrepostoservidor",
            name="cargo_base",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargos_sobrepostos",
                to="professores.cargobaseservidor",
            ),
        ),
        migrations.AlterField(
            model_name="contratoexterno",
            name="pessoa",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="professores.pessoa",
            ),
        ),
        migrations.AlterField(
            model_name="funcaoatividadecargoservidor",
            name="cargo_base",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funcoes_atividade",
                to="professores.cargobaseservidor",
            ),
        ),
        migrations.AlterField(
            model_name="laudomedico",
            name="cargo_base",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="laudos_medicos",
                to="professores.cargobaseservidor",
            ),
        ),
        migrations.AlterField(
            model_name="lotacaoservidor",
            name="cargo_base",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lotacoes",
                to="professores.cargobaseservidor",
            ),
        ),
    ]
