# Generated by Django 5.2.13 on 2026-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professores", "0003_alter_atribuicaoaula_cargo_base_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atribuicaoaula",
            name="codigo_grade",
            field=models.IntegerField(
                help_text="ID da escola_grade — ref. domínio pedagógico."
            ),
        ),
        migrations.AlterField(
            model_name="atribuicaoexterno",
            name="codigo_grade",
            field=models.IntegerField(
                help_text="ID da escola_grade — ref. domínio pedagógico."
            ),
        ),
    ]
