# Generated by Django 5.2.13 on 2026-05-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professores", "0007_cargobaseservidor_situacao_funcional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atribuicaoaula",
            name="codigo_unidade_educacao",
            field=models.CharField(
                help_text="ID da UnidadeEducacional neste DB.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="atribuicaoexterno",
            name="codigo_unidade_educacao",
            field=models.CharField(
                help_text="ID da UnidadeEducacional neste DB.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="cargobaseservidor",
            name="situacao_funcional",
            field=models.IntegerField(
                blank=True,
                help_text="cd_situacao_funcional — usado em VerificarValidadeProfessorAsync (filtro situacao = 6).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contratoexterno",
            name="codigo_unidade_educacao",
            field=models.CharField(
                help_text="ID da UnidadeEducacional neste DB.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="lotacaoservidor",
            name="codigo_unidade_educacao",
            field=models.CharField(
                help_text="ID da UnidadeEducacional neste DB.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="serieturmagrade",
            name="codigo_escola",
            field=models.CharField(
                help_text="ID da UnidadeEducacional neste DB.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="turmaescola",
            name="codigo_escola",
            field=models.CharField(
                help_text="ID da UnidadeEducacional neste DB.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="turmagradeterritorioexperiencia",
            name="codigo_serie_grade",
            field=models.IntegerField(
                help_text="ID da SerieTurmaGrade neste DB."
            ),
        ),
    ]
