# Generated by Django 5.2.14 on 2026-05-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "professores",
            "0008_alter_atribuicaoaula_codigo_unidade_educacao_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgrupamentoAtribuicaoTerritorioSaber",
        ),
        migrations.DeleteModel(
            name="SerieTurmaGrade",
        ),
        migrations.DeleteModel(
            name="TurmaEscola",
        ),
        migrations.DeleteModel(
            name="TurmaEscolaGradePrograma",
        ),
        migrations.DeleteModel(
            name="TurmaGradeTerritorioExperiencia",
        ),
        migrations.DeleteModel(
            name="UnidadeEducacional",
        ),
        migrations.AddField(
            model_name="atribuicaoexterno",
            name="codigo_turma_escola",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID da turma escolar — ref. domínio pedagógico.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cargobaseservidor",
            name="descricao_cargo",
            field=models.CharField(
                blank=True,
                help_text="Descrição normalizada do cargo (dc_cargo via JOIN cargo).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="atribuicaoaula",
            name="codigo_serie_grade",
            field=models.IntegerField(
                blank=True,
                help_text="ID de série-grade — ref. domínio pedagógico.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="atribuicaoaula",
            name="codigo_turma_escola",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID da turma escolar — ref. domínio pedagógico.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="atribuicaoaula",
            name="codigo_turma_escola_grade_programa",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID da grade/programa da turma.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="atribuicaoaula",
            name="codigo_unidade_educacao",
            field=models.CharField(
                help_text="ID da unidade educacional — ref. domínio institucional.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="atribuicaoexterno",
            name="codigo_serie_grade",
            field=models.IntegerField(
                blank=True,
                help_text="ID de série-grade — ref. domínio pedagógico.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="atribuicaoexterno",
            name="codigo_turma_escola_grade_programa",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID da grade/programa da turma.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="atribuicaoexterno",
            name="codigo_unidade_educacao",
            field=models.CharField(
                help_text="ID da unidade educacional — ref. domínio institucional.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contratoexterno",
            name="codigo_unidade_educacao",
            field=models.CharField(
                help_text="ID da unidade educacional — ref. domínio institucional.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lotacaoservidor",
            name="codigo_unidade_educacao",
            field=models.CharField(
                help_text="ID da unidade educacional — ref. domínio institucional.",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="atribuicaoexterno",
            index=models.Index(
                fields=["codigo_turma_escola"], name="idx_ae_turma"
            ),
        ),
    ]
