# Generated by Django 5.2.14 on 2026-05-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professores", "0009_ajustes_contexto_professores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargobaseservidor",
            name="descricao_cargo",
            field=models.CharField(
                blank=True,
                help_text="Descrição do cargo (dc_cargo via JOIN cargo).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FuncionarioUnidadeEducacional",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo_rf", models.CharField(max_length=20)),
                ("nome", models.CharField(max_length=200)),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("codigo_ue", models.CharField(max_length=20)),
                ("data_inicio", models.DateTimeField(blank=True, null=True)),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                (
                    "codigo_cargo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "codigo_tipo_funcao_atividade",
                    models.IntegerField(blank=True, null=True),
                ),
                ("eh_professor", models.BooleanField(default=False)),
                ("esta_afastado", models.BooleanField(default=False)),
                ("funcao_externo", models.IntegerField(default=0)),
                ("tipo_funcao_externo", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "funcionario",
                "verbose_name_plural": "funcionarios",
                "db_table": "funcionario_unidade_educacional",
                "indexes": [
                    models.Index(
                        fields=["codigo_ue"], name="idx_funcionario_ue"
                    ),
                    models.Index(
                        fields=["codigo_cargo"], name="idx_funcionario_cargo"
                    ),
                    models.Index(
                        fields=["codigo_rf"], name="idx_funcionario_rf"
                    ),
                    models.Index(
                        fields=["codigo_ue", "codigo_cargo"],
                        name="idx_funcionario_ue_cargo",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codigo_rf", "codigo_ue"),
                        name="uq_funcionario_rf_ue",
                    )
                ],
            },
        ),
    ]
