# Generated by Django 5.2.14 on 2026-05-27 13:25

import apps.professores.models
from django.db import migrations, models  # pragma: no cover


class Migration(migrations.Migration):

    dependencies = [  # pragma: no cover
        ("professores", "0010_funcionario_unidade_educacional_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="funcionariounidadeeducacional",
            name="uq_funcionario_rf_ue",
        ),
        migrations.AlterField(
            model_name="funcionariounidadeeducacional",
            name="codigo_cargo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="funcionariounidadeeducacional",
            name="codigo_tipo_funcao_atividade",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="funcionariounidadeeducacional",
            name="data_inicio",
            field=models.DateTimeField(
                default=apps.professores.models._data_chave_padrao
            ),
        ),
        migrations.AddConstraint(
            model_name="funcionariounidadeeducacional",
            constraint=models.UniqueConstraint(
                fields=(
                    "codigo_rf",
                    "codigo_ue",
                    "codigo_cargo",
                    "codigo_tipo_funcao_atividade",
                    "data_inicio",
                    "data_fim",
                    "funcao_externo",
                    "tipo_funcao_externo",
                ),
                name="uq_funcionario_rf_ue_cargo_funcao_vinculo",
                nulls_distinct=False,
            ),
        ),
    ]
