# Generated by Django 5.2.15 on 2026-07-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "professores",
            "0011_remove_funcionariounidadeeducacional_uq_funcionario_rf_ue_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="atribuicaoaula",
            name="ano_escolar",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="codigo_etapa_ensino",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="descricao_componente_curricular",
            field=models.CharField(
                blank=True,
                help_text="Descrição do componente curricular.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="descricao_turma_escola",
            field=models.CharField(
                blank=True,
                help_text="Descrição da turma escolar.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="atribuicaoexterno",
            name="ano_escolar",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoexterno",
            name="codigo_etapa_ensino",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoexterno",
            name="descricao_componente_curricular",
            field=models.CharField(
                blank=True,
                help_text="Descrição do componente curricular.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="atribuicaoexterno",
            name="descricao_turma_escola",
            field=models.CharField(
                blank=True,
                help_text="Descrição da turma escolar.",
                max_length=200,
                null=True,
            ),
        ),
    ]
