# Generated by Django 5.2.15 on 2026-07-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professores", "0012_atribuicaoaula_ano_escolar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atribuicaoaula",
            name="dt_inicio_turma",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoexterno",
            name="dt_inicio_turma",
            field=models.DateField(blank=True, null=True),
        ),
    ]
