# Generated by Django 5.2.16 on 2026-07-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professores", "0013_atribuicaoaula_dt_inicio_turma_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atribuicaoaula",
            name="abreviacao_dre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="codigo_dre",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="codigo_modalidade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="codigo_tipo_escola",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="codigo_tipo_turma",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="dt_fim_turma",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="duracao_turno",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="modalidade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="nome_dre",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="nome_unidade_educacional",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="semestre",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoaula",
            name="tipo_turno",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atribuicaoexterno",
            name="dt_fim_turma",
            field=models.DateField(blank=True, null=True),
        ),
    ]
