# Generated by Django 5.2.16 on 2026-08-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0022_funcionario_unidade_educacional_codigo_dre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ue', models.CharField(db_index=True, help_text='Código EOL da unidade educacional.', max_length=20)),
                ('rf_login', models.CharField(help_text='RF/Login do administrador no sistema SGP.', max_length=50)),
                ('data_sincronizacao', models.DateTimeField(auto_now=True, help_text='Data/hora da última sincronização do CoreSSO.')),
            ],
            options={
                'verbose_name': 'administrador SGP da escola',
                'verbose_name_plural': 'administradores SGP das escolas',
                'db_table': 'administrador_escola',
                'indexes': [models.Index(fields=['codigo_ue'], name='idx_adm_escola_ue')],
            },
        ),
    ]
