# Generated by Django 5.2.16 on 2026-08-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0023_adiciona_administrador_escola'),
    ]

    operations = [
        # Migration vazia - previne auto-geracao de AlterUniqueTogether
    ]
