# Generated by Django 5.2.17 on 2026-08-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professores", "0023_adiciona_administrador_escola"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionariounidadeeducacional",
            name="dc_funcao_externo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="funcionariounidadeeducacional",
            name="nome_ue",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="funcionariounidadeeducacional",
            name="pessoa",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="professores.pessoa",
            ),
        ),
        migrations.AddField(
            model_name="funcionariounidadeeducacional",
            name="supervisor_dre",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="funcionariounidadeeducacional",
            name="tipo_funcionario_externo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="nome_mae",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="nome_pai",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="pis_pasep",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="rg",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="pessoa",
            name="titulo_eleitoral",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
