# Generated by Django 5.2.17 on 2026-08-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "professores",
            "0024_funcionario_unidade_educacional_pessoa_dados_pessoais",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FuncionarioSistemaPerfil",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=500)),
                (
                    "nome_servidor",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "uad_codigo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("perfil", models.UUIDField()),
                ("sis_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "perfil de sistema do funcionario",
                "verbose_name_plural": "perfis de sistema dos funcionarios",
                "db_table": "funcionario_sistema_perfil",
                "indexes": [
                    models.Index(fields=["login"], name="idx_fsp_login"),
                    models.Index(fields=["sis_id"], name="idx_fsp_sis_id"),
                    models.Index(fields=["perfil"], name="idx_fsp_perfil"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("login", "perfil", "sis_id"),
                        name="uq_fsp_login_perfil_sis",
                    )
                ],
            },
        ),
    ]
