# ruff: noqa: D100,D101
# Generated by Django 5.2.12 on 2026-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professores", "0025_funcionario_sistema_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="atribuicaoaula",
            name="dt_disponibilizacao_aulas_origem",
            field=models.DateField(
                blank=True,
                help_text=(
                    "Data de disponibilização como consta na origem, sem "
                    "substituição. O nulo distingue a atribuição ainda ativa."
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="atribuicaoaula",
            name="dt_disponibilizacao_aulas",
            field=models.DateField(
                blank=True,
                help_text=(
                    "Data efetiva de fim da atribuição: quando a origem não "
                    "informa a disponibilização, assume a data de fim da "
                    "turma."
                ),
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FuncionarioConectaFormacao",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rf", models.CharField(max_length=20)),
                ("nome", models.CharField(max_length=200)),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("cargo_codigo", models.IntegerField(blank=True, null=True)),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "cargo_dre_codigo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cargo_ue_codigo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("funcao_codigo", models.IntegerField(blank=True, null=True)),
                (
                    "funcao",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "funcao_dre_codigo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "funcao_ue_codigo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("tipo_vinculo", models.IntegerField(blank=True, null=True)),
                (
                    "codigo_modalidade",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "ano_turma",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "codigo_componente_curricular",
                    models.IntegerField(blank=True, null=True),
                ),
                ("eh_tipo_jornada_jeif", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "funcionário do Conecta Formação",
                "verbose_name_plural": "funcionários do Conecta Formação",
                "db_table": "funcionario_conecta_formacao",
                "indexes": [
                    models.Index(fields=["rf"], name="idx_func_conecta_rf"),
                    models.Index(
                        fields=["cargo_codigo"], name="idx_func_conecta_cargo"
                    ),
                    models.Index(
                        fields=["funcao_codigo"],
                        name="idx_func_conecta_funcao",
                    ),
                    models.Index(
                        fields=["cargo_dre_codigo"],
                        name="idx_func_conecta_dre",
                    ),
                    models.Index(
                        fields=["codigo_modalidade", "ano_turma"],
                        name="idx_func_conecta_mod_ano",
                    ),
                    models.Index(
                        fields=["codigo_componente_curricular"],
                        name="idx_func_conecta_comp",
                    ),
                    models.Index(
                        fields=["cargo_codigo", "funcao_codigo"],
                        name="idx_func_conecta_cargo_func",
                    ),
                    models.Index(
                        fields=["cargo_ue_codigo"],
                        name="idx_func_conecta_cargo_ue",
                    ),
                    models.Index(
                        fields=["funcao_ue_codigo"],
                        name="idx_func_conecta_func_ue",
                    ),
                    models.Index(
                        fields=[
                            "codigo_modalidade",
                            "ano_turma",
                            "codigo_componente_curricular",
                        ],
                        name="idx_func_conecta_mod_ano_comp",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "rf",
                            "cargo_codigo",
                            "cargo_ue_codigo",
                            "funcao_codigo",
                            "funcao_ue_codigo",
                            "tipo_vinculo",
                            "codigo_modalidade",
                            "ano_turma",
                            "codigo_componente_curricular",
                        ),
                        name="uq_func_conecta_filtro",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FuncionarioConectaModalidadeEscola",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo_ue", models.CharField(max_length=20)),
                ("codigo_modalidade", models.IntegerField()),
            ],
            options={
                "verbose_name": "modalidade por unidade do Conecta Formação",
                "verbose_name_plural": (
                    "modalidades por unidade do Conecta Formação"
                ),
                "db_table": "funcionario_conecta_modalidade_escola",
                "indexes": [
                    models.Index(
                        fields=["codigo_modalidade", "codigo_ue"],
                        name="idx_func_conecta_mod_ue",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codigo_ue", "codigo_modalidade"),
                        name="uq_func_conecta_mod_ue",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FuncionarioVinculoFuncional",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rf", models.CharField(max_length=20)),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("cd_cargo_base", models.IntegerField(blank=True, null=True)),
                (
                    "cargo_base",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "cd_dre_cargo_base",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cd_ue_cargo_base",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "ue_cargo_base",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "tipo_vinculo_cargo_base",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "data_inicio_cargo_base",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "cd_cargo_sobreposto",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "cargo_sobreposto",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "cd_dre_cargo_sobreposto",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cd_ue_cargo_sobreposto",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "ue_cargo_sobreposto",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "tipo_vinculo_cargo_sobreposto",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "data_inicio_cargo_sobreposto",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "cd_funcao_atividade",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "funcao_atividade",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "cd_dre_funcao_atividade",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cd_ue_funcao_atividade",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "ue_funcao_atividade",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "tipo_vinculo_funcao_atividade",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "data_inicio_funcao_atividade",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "dt_cancelamento_funcao_atividade",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "dt_fim_funcao_atividade",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "vínculo funcional do funcionário",
                "verbose_name_plural": "vínculos funcionais dos funcionários",
                "db_table": "funcionario_vinculo_funcional",
                "indexes": [
                    models.Index(fields=["rf"], name="idx_func_vinc_func_rf"),
                    models.Index(
                        fields=["rf", "cd_cargo_base"],
                        name="idx_func_vinc_func_rf_cb",
                    ),
                    models.Index(
                        fields=["cd_ue_cargo_base"],
                        name="idx_func_vinc_func_ue_cb",
                    ),
                    models.Index(
                        fields=["cd_dre_cargo_base"],
                        name="idx_func_vinc_func_dre_cb",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "rf",
                            "cd_cargo_base",
                            "cd_ue_cargo_base",
                            "tipo_vinculo_cargo_base",
                            "cd_cargo_sobreposto",
                            "cd_ue_cargo_sobreposto",
                            "tipo_vinculo_cargo_sobreposto",
                            "cd_funcao_atividade",
                            "cd_ue_funcao_atividade",
                            "tipo_vinculo_funcao_atividade",
                        ),
                        name="uq_func_vinc_func_vinculo",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfessorEscolaAno",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("origem", models.CharField(max_length=20)),
                (
                    "codigo_escola",
                    models.CharField(
                        help_text=(
                            "ID da unidade educacional — ref. domínio "
                            "institucional."
                        ),
                        max_length=20,
                    ),
                ),
                ("ano_letivo", models.IntegerField()),
                (
                    "codigo_turma",
                    models.BigIntegerField(
                        help_text=(
                            "ID da turma escolar — ref. domínio pedagógico."
                        )
                    ),
                ),
                ("codigo_rf", models.CharField(max_length=20)),
                (
                    "codigo_componente_curricular",
                    models.IntegerField(
                        help_text=(
                            "ID do componente curricular — ref. domínio "
                            "curricular."
                        )
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "data_inicio_exercicio",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "professor por escola e ano",
                "verbose_name_plural": "professores por escola e ano",
                "db_table": "professor_escola_ano",
                "indexes": [
                    models.Index(
                        fields=["codigo_escola", "ano_letivo"],
                        name="idx_prof_esc_ano_ue_ano",
                    ),
                    models.Index(
                        fields=["codigo_rf"], name="idx_prof_esc_ano_rf"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "origem",
                            "codigo_escola",
                            "ano_letivo",
                            "codigo_turma",
                            "codigo_rf",
                            "codigo_componente_curricular",
                            "cargo",
                            "cpf",
                            "data_inicio_exercicio",
                        ),
                        name="uq_prof_esc_ano_legado",
                    )
                ],
            },
        ),
    ]
