# Generated by Django 5.2.17 on 2026-09-22 19:44

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        (
            "professores",
            "0026_atribuicaoaula_dt_disponibilizacao_aulas_origem_and_more",
        ),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="cargobaseservidor",
            index=models.Index(
                condition=models.Q(("dt_fim_nomeacao__isnull", True)),
                fields=["professor"],
                name="idx_cargobaseservidor_ativorf",
            ),
        ),
    ]
