# Generated by Django 5.2.13 on 2026-04-14 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoNecessidadeEspecial",
            fields=[
                (
                    "codigo_necessidade_especial",
                    models.SmallIntegerField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                (
                    "codigo_estado",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("data_cancelamento", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "tipo de necessidade especial",
                "verbose_name_plural": "tipos de necessidades especiais",
                "db_table": "tipo_necessidade_especial",
            },
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "codigo_aluno",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                (
                    "sexo",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "nome_mae",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "nacionalidade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nis",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "raca_cor",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "aluno",
                "verbose_name_plural": "alunos",
                "db_table": "aluno",
                "indexes": [
                    models.Index(fields=["nome"], name="idx_aluno_nome")
                ],
            },
        ),
        migrations.CreateModel(
            name="MatriculaTurma",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_matricula",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("codigo_turma", models.BigIntegerField()),
                (
                    "numero_chamada",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "data_situacao_aluno",
                    models.DateField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "matricula_turma",
                "indexes": [
                    models.Index(
                        fields=["codigo_turma"],
                        name="idx_matricula_turma_codigo",
                    )
                ],
                "unique_together": {("codigo_matricula", "codigo_turma")},
            },
        ),
        migrations.CreateModel(
            name="ResponsavelAluno",
            fields=[
                (
                    "codigo_responsavel",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "tipo_responsavel",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "ddd_celular",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "numero_celular",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=200, null=True),
                ),
                (
                    "autoriza_sms",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "logradouro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cep", models.IntegerField(blank=True, null=True)),
                ("data_fim_vinculo", models.DateField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        db_column="codigo_aluno",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsaveis",
                        to="alunos.aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "responsável",
                "verbose_name_plural": "responsáveis",
                "db_table": "responsavel_aluno",
            },
        ),
        migrations.CreateModel(
            name="NecessidadeEspecialAluno",
            fields=[
                (
                    "codigo_necessidade_especial_aluno",
                    models.BigIntegerField(
                        help_text="ID original do EOL (cd_identificador...)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        db_column="codigo_aluno",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="necessidades",
                        to="alunos.aluno",
                    ),
                ),
                (
                    "necessidade_especial",
                    models.ForeignKey(
                        db_column="codigo_necessidade_especial",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alunos.tiponecessidadeespecial",
                    ),
                ),
            ],
            options={
                "db_table": "necessidade_especial_aluno",
            },
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "codigo_matricula",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("codigo_ue", models.CharField(max_length=20)),
                ("ano_letivo", models.SmallIntegerField()),
                ("data_status", models.DateField(blank=True, null=True)),
                ("codigo_situacao_matricula", models.SmallIntegerField()),
                ("situacao_matricula", models.CharField(max_length=100)),
                (
                    "aluno",
                    models.ForeignKey(
                        db_column="codigo_aluno",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="alunos.aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "matrícula",
                "verbose_name_plural": "matrículas",
                "db_table": "matricula",
                "indexes": [
                    models.Index(
                        fields=["codigo_ue"], name="idx_matricula_codigo_ue"
                    ),
                    models.Index(
                        fields=["ano_letivo"], name="idx_matricula_ano_letivo"
                    ),
                ],
            },
        ),
    ]
