# Generated by Django 5.2.13 on 2026-04-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matriculaturma",
            name="matricula",
            field=models.ForeignKey(
                db_column="codigo_matricula",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matriculas_turmas",
                to="alunos.matricula",
            ),
        ),
    ]
