# Generated by Django 5.2.14 on 2026-05-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_aluno_novos_campos_matricula_renomear_data_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosAlunoAcompanhamentoEscolar",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo_aluno", models.BigIntegerField()),
                ("nome", models.CharField(max_length=200)),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "nome_responsavel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "cpf_responsavel",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("descricao_tipo_escola", models.CharField(max_length=50)),
                (
                    "tipo_responsavel",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("codigo_dre", models.CharField(max_length=20)),
                (
                    "sigla_dre",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("codigo_ue", models.CharField(max_length=20)),
                ("unidade_educacional", models.CharField(max_length=300)),
                ("codigo_turma", models.BigIntegerField()),
                ("turma", models.CharField(max_length=100)),
                ("codigo_tipo_escola", models.SmallIntegerField()),
                ("situacao_matricula", models.CharField(max_length=100)),
                (
                    "data_situacao_matricula",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "codigo_etapa_ensino",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "codigo_ciclo_ensino",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "serie_resumida",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "codigo_modalidade_turma",
                    models.SmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "dados_aluno_acompanhamento_escolar",
                "unique_together": {
                    ("codigo_aluno", "codigo_turma", "tipo_responsavel")
                },
            },
        ),
        migrations.CreateModel(
            name="MatriculaAnoLetivo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo_dre", models.CharField(max_length=20)),
                ("codigo_ue", models.CharField(max_length=20)),
                ("tipo_escola", models.SmallIntegerField()),
                ("ano_letivo", models.SmallIntegerField()),
                (
                    "codigo_modalidade",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "modalidade",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("ordem", models.SmallIntegerField(blank=True, null=True)),
                (
                    "ano",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "turma",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantidade", models.IntegerField()),
            ],
            options={
                "db_table": "matricula_ano_letivo",
                "unique_together": {
                    (
                        "codigo_dre",
                        "codigo_ue",
                        "tipo_escola",
                        "ano_letivo",
                        "modalidade",
                        "ano",
                        "turma",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="MatriculaComponenteCurricularAnoLetivo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo_ue", models.CharField(max_length=20)),
                ("codigo_dre", models.CharField(max_length=20)),
                ("ano_letivo", models.SmallIntegerField()),
                (
                    "modalidade",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("ordem", models.SmallIntegerField(blank=True, null=True)),
                ("componente_curricular_id", models.IntegerField()),
                (
                    "ano",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "turma",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantidade", models.IntegerField()),
            ],
            options={
                "db_table": "matricula_componente_curricular_ano_letivo",
                "unique_together": {
                    (
                        "codigo_ue",
                        "codigo_dre",
                        "ano_letivo",
                        "modalidade",
                        "componente_curricular_id",
                        "ano",
                    )
                },
            },
        ),
    ]
