# Generated by Django 5.2.15 on 2026-06-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0009_add_unique_constraints_chaves_primarias"),
    ]

    operations = [
        migrations.AddField(
            model_name="matriculaturma",
            name="codigo_etapa_ensino",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matriculaturma",
            name="nome_turma",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
