# Generated by Django 5.2.15 on 2026-06-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0011_merge_20260615_1537"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matriculaturma",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="matricula",
            name="codigo_dre",
            field=models.CharField(default="000000", max_length=20),
        ),
        migrations.AddField(
            model_name="matriculaturma",
            name="sequencia",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="matriculaturma",
            unique_together={
                (
                    "codigo_matricula",
                    "codigo_turma",
                    "codigo_situacao_aluno",
                    "sequencia",
                )
            },
        ),
        migrations.AddIndex(
            model_name="matricula",
            index=models.Index(
                fields=["codigo_dre"], name="idx_matricula_codigo_dre"
            ),
        ),
    ]
