# Generated by Django 5.2.15 on 2026-06-22

"""Inclui campos complementares na listagem de alunos por UE."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Aplica a evolução de dados da listagem de alunos por UE."""

    dependencies = [
        ("alunos", "0013_remove_unique_obsoleta_matricula_turma"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadosalunoacompanhamentoescolar",
            name="descricao_ciclo_ensino",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dadosalunoacompanhamentoescolar",
            name="descricao_etapa_ensino",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="matriculaturma",
            name="tipo_turno",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
