# Generated by Django 5.2.15 on 2026-06-22

"""Inclui telefones residencial e comercial de responsáveis."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Aplica a evolução de telefones dos responsáveis."""

    dependencies = [
        ("alunos", "0014_ep2_campos_listagem_alunos_ue"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsavelaluno",
            name="ddd_telefone_comercial",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="responsavelaluno",
            name="ddd_telefone_fixo",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="responsavelaluno",
            name="nr_telefone_comercial",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="responsavelaluno",
            name="nr_telefone_fixo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
