# Generated by Django 5.2.15 on 2026-06-22

"""Inclui flag de origem e ano letivo da turma na matrícula-turma."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Aplica os campos de origem e ano letivo da turma (EP2/EP4)."""

    dependencies = [
        ("alunos", "0015_ep5_telefones_responsavel_aluno"),
    ]

    operations = [
        migrations.AddField(
            model_name="matriculaturma",
            name="ano_letivo_turma",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matriculaturma",
            name="origem_atual",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
