# Generated by Codex on 2026-06-25

"""Inclui campos de UE, etapa e ciclo da turma para EP2."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Aplica campos derivados da turma usados pela listagem EP2."""

    dependencies = [
        ("alunos", "0016_ep2_ep4_origem_atual_ano_turma"),
    ]

    operations = [
        migrations.AddField(
            model_name="matriculaturma",
            name="codigo_ue_turma",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="matriculaturma",
            name="codigo_ciclo_ensino",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matriculaturma",
            name="descricao_etapa_ensino",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="matriculaturma",
            name="descricao_ciclo_ensino",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
