# Generated by Django 5.2.15 on 2026-06-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0017_ep2_campos_serie_turma"),
    ]

    operations = [
        migrations.AddField(
            model_name="matriculaturma",
            name="serie_resumida",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
