# Generated by Django 5.2.15 on 2026-07-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0018_matriculaturma_serie_resumida"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadosalunoacompanhamentoescolar",
            name="data_fim_vinculo_responsavel",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dadosalunoacompanhamentoescolar",
            name="data_situacao_matricula_data_hora",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dadosalunoacompanhamentoescolar",
            name="tipo_sigilo",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
