# Generated by Django 5.2.15 on 2026-07-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "alunos",
            "0019_dadosalunoacompanhamentoescolar_data_fim_vinculo_responsavel_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matriculacomponentecurricularanoletivo",
            unique_together={
                (
                    "codigo_ue",
                    "codigo_dre",
                    "ano_letivo",
                    "modalidade",
                    "componente_curricular_id",
                    "ano",
                    "turma",
                )
            },
        ),
    ]
