# Generated by Django 5.2.16 on 2026-07-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "alunos",
            "0020_alter_matriculacomponentecurricularanoletivo_unique_together",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="presente_historico",
            field=models.BooleanField(default=False),
        ),
    ]
