# Generated by Django 5.2.15 on 2026-07-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "alunos",
            "0020_alter_matriculacomponentecurricularanoletivo_unique_together",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="origem_historica",
            field=models.BooleanField(default=False),
        ),
    ]
