# Generated by Django 5.2.15 on 2026-07-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0021_matricula_origem_historica"),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="data_situacao_matricula_historica",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
