# Generated by Django 5.2.1 on 2026-07-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0023_responsavel_aluno_turma_matricula_ano_anterior"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="tipo_sigilo",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matricula",
            name="codigo_serie_ensino",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matricula",
            name="codigo_tipo_escola",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="responsavelaluno",
            name="cpf_confere",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="responsavelaluno",
            name="digito_rg",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="responsavelaluno",
            name="numero_rg",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="responsavelaluno",
            name="tipo_turno_celular",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="responsavelaluno",
            name="tipo_turno_comercial",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="responsavelaluno",
            name="tipo_turno_fixo",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="responsavelaluno",
            name="uf_rg",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name="responsavelaluno",
            index=models.Index(
                fields=["cpf", "data_fim_vinculo", "aluno"],
                name="idx_resp_cpf_fim_aluno",
            ),
        ),
    ]
